# src/game_items.py
"""
Words for the picture games, each linked to an image.

Images are bundled in data/game_images (see game_images.py): Twemoji
graphics (CC-BY 4.0) named by code point - "tw:1f455" - or photos and
illustrations from Wikimedia Commons - "wm:durian", "wm:knee" - whose
author, licence and source are recorded in data/game_images/credits.json.

Malaysian usage throughout: 恤衫, 冰厨, 冷气, 锁匙, 朱古力, 雪糕, 黄梨, 德士…
"""

CATEGORIES = {
    "body": ("身体", "Body", "💪"),
    "clothing": ("衣服", "Clothing", "👕"),
    "food": ("食物", "Food & drink", "🍜"),
    "home": ("家里", "Home & daily life", "🏠"),
    "places": ("交通和地方", "Transport & places", "🚌"),
    "nature": ("大自然", "Nature & weather", "🌳"),
    "animals": ("动物", "Animals", "🐈"),
    "tcm": ("中医诊所", "TCM clinic", "🌿"),
}

_I = lambda cat, zh, py, en, img: {"category": cat, "chinese": zh, "pinyin": py,
                                   "english": en, "image": img}

ITEMS = [
    # ---- body -----------------------------------------------------------
    _I("body", "头", "tóu", "head", "wm:head"),
    _I("body", "头发", "tóu fa", "hair", "wm:hair"),
    _I("body", "脸", "liǎn", "face", "wm:face"),
    _I("body", "额头", "é tóu", "forehead", "wm:forehead"),
    _I("body", "眉毛", "méi mao", "eyebrow", "wm:eyebrow"),
    _I("body", "下巴", "xià ba", "chin", "wm:chin"),
    _I("body", "眼睛", "yǎn jing", "eye", "tw:1f441"),
    _I("body", "耳朵", "ěr duo", "ear", "tw:1f442"),
    _I("body", "鼻子", "bí zi", "nose", "tw:1f443"),
    _I("body", "嘴巴", "zuǐ ba", "mouth", "tw:1f444"),
    _I("body", "牙齿", "yá chǐ", "tooth / teeth", "tw:1f9b7"),
    _I("body", "舌头", "shé tou", "tongue", "tw:1f445"),
    _I("body", "颈项", "jǐng xiàng", "neck", "wm:neck"),
    _I("body", "肩膀", "jiān bǎng", "shoulder", "wm:shoulder"),
    _I("body", "手臂", "shǒu bì", "arm", "wm:arm"),
    _I("body", "手肘", "shǒu zhǒu", "elbow", "wm:elbow"),
    _I("body", "手腕", "shǒu wàn", "wrist", "wm:wrist"),
    _I("body", "手", "shǒu", "hand", "tw:270b"),
    _I("body", "手指", "shǒu zhǐ", "finger", "tw:261d"),
    _I("body", "指甲", "zhǐ jiǎ", "fingernail", "tw:1f485"),
    _I("body", "胸口", "xiōng kǒu", "chest", "wm:chest"),
    _I("body", "肚子", "dù zi", "belly", "wm:belly"),
    _I("body", "背", "bèi", "back", "wm:back"),
    _I("body", "腰", "yāo", "waist / lower back", "wm:waist"),
    _I("body", "屁股", "pì gu", "buttocks", "wm:buttocks"),
    _I("body", "腿", "tuǐ", "leg", "tw:1f9b5"),
    _I("body", "膝盖", "xī gài", "knee", "wm:knee"),
    _I("body", "脚踝", "jiǎo huái", "ankle", "wm:ankle"),
    _I("body", "脚", "jiǎo", "foot", "tw:1f9b6"),
    _I("body", "心", "xīn", "heart", "tw:1fac0"),
    _I("body", "肺", "fèi", "lungs", "tw:1fac1"),
    _I("body", "大脑", "dà nǎo", "brain", "tw:1f9e0"),
    _I("body", "胃", "wèi", "stomach", "wm:stomach"),
    _I("body", "肝", "gān", "liver", "wm:liver"),
    _I("body", "肾", "shèn", "kidney", "wm:kidney"),
    _I("body", "骨头", "gǔ tou", "bone", "tw:1f9b4"),
    _I("body", "血", "xuè", "blood", "tw:1fa78"),

    # ---- clothing ---------------------------------------------------------
    _I("clothing", "恤衫", "xù shān", "shirt / T-shirt", "tw:1f455"),
    _I("clothing", "裤子", "kù zi", "trousers", "tw:1f456"),
    _I("clothing", "短裤", "duǎn kù", "shorts", "tw:1fa73"),
    _I("clothing", "裙子", "qún zi", "dress / skirt", "tw:1f457"),
    _I("clothing", "外套", "wài tào", "jacket / coat", "tw:1f9e5"),
    _I("clothing", "鞋子", "xié zi", "shoes", "tw:1f45f"),
    _I("clothing", "拖鞋", "tuō xié", "flip-flops / slippers", "tw:1fa74"),
    _I("clothing", "高跟鞋", "gāo gēn xié", "high heels", "tw:1f460"),
    _I("clothing", "袜子", "wà zi", "socks", "tw:1f9e6"),
    _I("clothing", "帽子", "mào zi", "hat / cap", "tw:1f9e2"),
    _I("clothing", "眼镜", "yǎn jìng", "glasses", "tw:1f453"),
    _I("clothing", "太阳眼镜", "tài yáng yǎn jìng", "sunglasses", "tw:1f576"),
    _I("clothing", "手表", "shǒu biǎo", "watch", "tw:231a"),
    _I("clothing", "领带", "lǐng dài", "tie", "tw:1f454"),
    _I("clothing", "背包", "bēi bāo", "backpack", "tw:1f392"),
    _I("clothing", "手提包", "shǒu tí bāo", "handbag", "tw:1f45c"),
    _I("clothing", "钱包", "qián bāo", "purse / wallet", "tw:1f45b"),
    _I("clothing", "围巾", "wéi jīn", "scarf", "tw:1f9e3"),
    _I("clothing", "手套", "shǒu tào", "gloves", "tw:1f9e4"),
    _I("clothing", "戒指", "jiè zhi", "ring", "tw:1f48d"),
    _I("clothing", "泳衣", "yǒng yī", "swimsuit", "tw:1fa71"),

    # ---- food & drink -----------------------------------------------------
    _I("food", "饭", "fàn", "rice (cooked) / meal", "tw:1f35a"),
    _I("food", "面", "miàn", "noodles", "tw:1f35c"),
    _I("food", "面包", "miàn bāo", "bread", "tw:1f35e"),
    _I("food", "鸡蛋", "jī dàn", "egg", "tw:1f95a"),
    _I("food", "虾", "xiā", "prawn", "tw:1f990"),
    _I("food", "肉", "ròu", "meat", "tw:1f969"),
    _I("food", "汤", "tāng", "soup", "tw:1f372"),
    _I("food", "饺子", "jiǎo zi", "dumpling", "tw:1f95f"),
    _I("food", "苹果", "píng guǒ", "apple", "tw:1f34e"),
    _I("food", "香蕉", "xiāng jiāo", "banana", "tw:1f34c"),
    _I("food", "橙", "chéng", "orange", "tw:1f34a"),
    _I("food", "西瓜", "xī guā", "watermelon", "tw:1f349"),
    _I("food", "榴莲", "liú lián", "durian", "wm:durian"),
    _I("food", "椰子", "yē zi", "coconut", "tw:1f965"),
    _I("food", "芒果", "máng guǒ", "mango", "tw:1f96d"),
    _I("food", "葡萄", "pú tao", "grapes", "tw:1f347"),
    _I("food", "黄梨", "huáng lí", "pineapple (Malaysian)", "tw:1f34d"),
    _I("food", "辣椒", "là jiāo", "chilli", "tw:1f336"),
    _I("food", "蒜头", "suàn tóu", "garlic", "tw:1f9c4"),
    _I("food", "洋葱", "yáng cōng", "onion", "tw:1f9c5"),
    _I("food", "番茄", "fān qié", "tomato", "tw:1f345"),
    _I("food", "马铃薯", "mǎ líng shǔ", "potato", "tw:1f954"),
    _I("food", "红萝卜", "hóng luó bo", "carrot", "tw:1f955"),
    _I("food", "玉米", "yù mǐ", "corn", "tw:1f33d"),
    _I("food", "茶", "chá", "tea", "tw:1f375"),
    _I("food", "咖啡", "kā fēi", "coffee", "tw:2615"),
    _I("food", "牛奶", "niú nǎi", "milk", "tw:1f95b"),
    _I("food", "啤酒", "pí jiǔ", "beer", "tw:1f37a"),
    _I("food", "雪糕", "xuě gāo", "ice cream", "tw:1f366"),
    _I("food", "蛋糕", "dàn gāo", "cake", "tw:1f370"),
    _I("food", "朱古力", "zhū gǔ lì", "chocolate", "tw:1f36b"),
    _I("food", "饼干", "bǐng gān", "biscuit", "tw:1f36a"),
    _I("food", "糖果", "táng guǒ", "sweets", "tw:1f36c"),
    _I("food", "盐", "yán", "salt", "tw:1f9c2"),
    _I("food", "冰", "bīng", "ice", "tw:1f9ca"),

    # ---- home & daily life ------------------------------------------------
    _I("home", "床", "chuáng", "bed", "tw:1f6cf"),
    _I("home", "椅子", "yǐ zi", "chair", "tw:1fa91"),
    _I("home", "桌子", "zhuō zi", "table", "wm:table"),
    _I("home", "门", "mén", "door", "tw:1f6aa"),
    _I("home", "窗口", "chuāng kǒu", "window", "tw:1fa9f"),
    _I("home", "冷气", "lěng qì", "air-con", "wm:aircon"),
    _I("home", "冰厨", "bīng chú", "fridge", "wm:fridge"),
    _I("home", "洗衣机", "xǐ yī jī", "washing machine", "wm:washer"),
    _I("home", "风扇", "fēng shàn", "fan", "wm:fan"),
    _I("home", "电视", "diàn shì", "television", "tw:1f4fa"),
    _I("home", "电脑", "diàn nǎo", "computer", "tw:1f4bb"),
    _I("home", "手机", "shǒu jī", "mobile phone", "tw:1f4f1"),
    _I("home", "锁匙", "suǒ shi", "key", "tw:1f511"),
    _I("home", "灯", "dēng", "light / lamp", "tw:1f4a1"),
    _I("home", "书", "shū", "book", "tw:1f4d6"),
    _I("home", "笔", "bǐ", "pen", "tw:1f58a"),
    _I("home", "纸", "zhǐ", "paper", "tw:1f4c4"),
    _I("home", "杯子", "bēi zi", "glass / cup", "tw:1f943"),
    _I("home", "碗", "wǎn", "bowl", "tw:1f963"),
    _I("home", "筷子", "kuài zi", "chopsticks", "tw:1f962"),
    _I("home", "汤匙", "tāng chí", "spoon", "tw:1f944"),
    _I("home", "刀", "dāo", "knife", "tw:1f52a"),
    _I("home", "剪刀", "jiǎn dāo", "scissors", "tw:2702"),
    _I("home", "钱", "qián", "money", "tw:1f4b5"),
    _I("home", "牙刷", "yá shuā", "toothbrush", "tw:1faa5"),
    _I("home", "肥皂", "féi zào", "soap", "tw:1f9fc"),
    _I("home", "镜子", "jìng zi", "mirror", "tw:1fa9e"),
    _I("home", "时钟", "shí zhōng", "clock", "tw:1f570"),
    _I("home", "垃圾桶", "lā jī tǒng", "rubbish bin", "tw:1f5d1"),
    _I("home", "照片", "zhào piàn", "photo / picture", "tw:1f5bc"),
    _I("home", "礼物", "lǐ wù", "present", "tw:1f381"),
    _I("home", "信", "xìn", "letter", "tw:2709"),
    _I("home", "蜡烛", "là zhú", "candle", "tw:1f56f"),

    # ---- transport & places -----------------------------------------------
    _I("places", "车", "chē", "car", "tw:1f697"),
    _I("places", "巴士", "bā shì", "bus", "tw:1f68c"),
    _I("places", "德士", "dé shì", "taxi", "tw:1f695"),
    _I("places", "脚踏车", "jiǎo tà chē", "bicycle", "tw:1f6b2"),
    _I("places", "摩托车", "mó tuō chē", "motorbike", "tw:1f3cd"),
    _I("places", "罗厘", "luó lí", "lorry", "tw:1f69a"),
    _I("places", "飞机", "fēi jī", "aeroplane", "tw:2708"),
    _I("places", "船", "chuán", "ship / boat", "tw:1f6a2"),
    _I("places", "火车", "huǒ chē", "train", "tw:1f686"),
    _I("places", "红绿灯", "hóng lǜ dēng", "traffic lights", "tw:1f6a6"),
    _I("places", "油站", "yóu zhàn", "petrol station", "tw:26fd"),
    _I("places", "家", "jiā", "home / house", "tw:1f3e0"),
    _I("places", "医院", "yī yuàn", "hospital", "tw:1f3e5"),
    _I("places", "学校", "xué xiào", "school", "tw:1f3eb"),
    _I("places", "银行", "yín háng", "bank", "tw:1f3e6"),
    _I("places", "酒店", "jiǔ diàn", "hotel", "tw:1f3e8"),
    _I("places", "商店", "shāng diàn", "shop", "tw:1f3ea"),
    _I("places", "海边", "hǎi biān", "beach / seaside", "tw:1f3d6"),
    _I("places", "山", "shān", "mountain / hill", "tw:26f0"),
    _I("places", "桥", "qiáo", "bridge", "tw:1f309"),

    # ---- nature & weather -------------------------------------------------
    _I("nature", "太阳", "tài yáng", "sun", "tw:2600"),
    _I("nature", "月亮", "yuè liang", "moon", "tw:1f319"),
    _I("nature", "星星", "xīng xing", "star", "tw:2b50"),
    _I("nature", "云", "yún", "cloud", "tw:2601"),
    _I("nature", "雨", "yǔ", "rain", "tw:1f327"),
    _I("nature", "风", "fēng", "wind", "tw:1f4a8"),
    _I("nature", "闪电", "shǎn diàn", "lightning", "tw:26a1"),
    _I("nature", "彩虹", "cǎi hóng", "rainbow", "tw:1f308"),
    _I("nature", "雪", "xuě", "snow", "tw:2744"),
    _I("nature", "火", "huǒ", "fire", "tw:1f525"),
    _I("nature", "海", "hǎi", "sea", "tw:1f30a"),
    _I("nature", "树", "shù", "tree", "tw:1f333"),
    _I("nature", "花", "huā", "flower", "tw:1f338"),
    _I("nature", "草", "cǎo", "grass / herb", "tw:1f33f"),
    _I("nature", "叶子", "yè zi", "leaf", "tw:1f343"),

    # ---- animals ------------------------------------------------------------
    _I("animals", "狗", "gǒu", "dog", "tw:1f415"),
    _I("animals", "猫", "māo", "cat", "tw:1f408"),
    _I("animals", "鸡", "jī", "chicken", "tw:1f414"),
    _I("animals", "鸭", "yā", "duck", "tw:1f986"),
    _I("animals", "鱼", "yú", "fish", "tw:1f41f"),
    _I("animals", "鸟", "niǎo", "bird", "tw:1f426"),
    _I("animals", "猪", "zhū", "pig", "tw:1f416"),
    _I("animals", "牛", "niú", "cow", "tw:1f404"),
    _I("animals", "羊", "yáng", "sheep / goat", "tw:1f411"),
    _I("animals", "马", "mǎ", "horse", "tw:1f40e"),
    _I("animals", "猴子", "hóu zi", "monkey", "tw:1f412"),
    _I("animals", "老鼠", "lǎo shǔ", "rat / mouse", "tw:1f400"),
    _I("animals", "蛇", "shé", "snake", "tw:1f40d"),
    _I("animals", "老虎", "lǎo hǔ", "tiger", "tw:1f405"),
    _I("animals", "大象", "dà xiàng", "elephant", "tw:1f418"),
    _I("animals", "乌龟", "wū guī", "tortoise", "tw:1f422"),
    _I("animals", "蝴蝶", "hú dié", "butterfly", "tw:1f98b"),
    _I("animals", "蚂蚁", "mǎ yǐ", "ant", "tw:1f41c"),
    _I("animals", "蚊子", "wén zi", "mosquito", "tw:1f99f"),
    _I("animals", "蟑螂", "zhāng láng", "cockroach", "tw:1fab3"),

    # ---- TCM clinic ------------------------------------------------------------
    _I("tcm", "针灸", "zhēn jiǔ", "acupuncture", "wm:acupuncture"),
    _I("tcm", "拔罐", "bá guàn", "cupping", "wm:cupping"),
    _I("tcm", "刮痧", "guā shā", "gua sha (scraping)", "wm:guasha"),
    _I("tcm", "艾灸", "ài jiǔ", "moxibustion", "wm:moxa"),
    _I("tcm", "把脉", "bǎ mài", "taking the pulse", "wm:pulse"),
    _I("tcm", "穴位", "xué wèi", "acupoint", "wm:acupoint"),
    _I("tcm", "按摩", "àn mó", "massage", "tw:1f486"),
    _I("tcm", "中药", "zhōng yào", "Chinese herbal medicine", "wm:herbs"),
    _I("tcm", "凉茶", "liáng chá", "herbal tea", "wm:herbaltea"),
    _I("tcm", "人参", "rén shēn", "ginseng", "wm:ginseng"),
    _I("tcm", "枸杞", "gǒu qǐ", "goji berries", "wm:goji"),
    _I("tcm", "药油", "yào yóu", "medicated oil", "wm:oil"),
    _I("tcm", "药丸", "yào wán", "pill", "tw:1f48a"),
    _I("tcm", "膏药", "gāo yao", "medicated plaster", "tw:1fa79"),
    _I("tcm", "体温计", "tǐ wēn jì", "thermometer", "tw:1f321"),
    _I("tcm", "听诊器", "tīng zhěn qì", "stethoscope", "tw:1fa7a"),
    _I("tcm", "口罩", "kǒu zhào", "face mask", "tw:1f637"),
    _I("tcm", "发烧", "fā shāo", "to have a fever", "tw:1f912"),
    _I("tcm", "打喷嚏", "dǎ pēn tì", "to sneeze", "tw:1f927"),
    _I("tcm", "头晕", "tóu yūn", "dizzy", "tw:1f635-200d-1f4ab"),
    _I("tcm", "受伤", "shòu shāng", "to be injured", "tw:1f915"),
    _I("tcm", "医生", "yī shēng", "doctor", "tw:1f9d1-200d-2695-fe0f"),
]


def by_category(categories=None):
    cats = set(categories or CATEGORIES)
    return [i for i in ITEMS if i["category"] in cats]
