# src/grammar_data_4.py
"""Grammar curriculum, groups 15-22: conjunctions, the 一/就/才/还/又/再
system, focus, scope, simultaneous actions, relative clauses, location,
movement."""

from grammar_schema import Structure

SECTIONS = {
    15: "Conjunctions & Logical Relationships",
    16: "一 / 就 / 才 / 还 / 又 / 再 System",
    17: "Focus, Emphasis & Limitation",
    18: "Addition, Exclusion & Scope",
    19: "Simultaneous & Related Actions",
    20: "Relative Clauses & Noun Modification",
    21: "Location & Existence",
    22: "Direction, Movement & Path",
}

_S = Structure
_CONJ = ("Both halves are normally said in Chinese even where English uses one "
         "word (虽然……但是……). 就 / 才 / 也 / 都 in the second half go after its "
         "subject, before the verb. ")
_JIUCAI = ("就 and 才 carry the speaker's expectation: 就 = earlier / sooner / easier "
           "than expected; 才 = later / harder / fewer than expected. Drill hearing "
           "the attitude, not a rule. ")
_REL = ("Everything describing a noun comes BEFORE it, joined with 的 (English "
        "puts clauses after). ")

STRUCTURES = [
    # ------------------------------------------------------------------
    # 15. Conjunctions — cause
    # ------------------------------------------------------------------
    _S("yinwei_suoyi", 15, "因为……所以…… — because … so …", "因为下雨，所以我没去。",
       "Give a reason and its result.",
       notes=_CONJ + "In speech either half can be used alone; 因为 can also follow "
             "(我没去，因为下雨).",
       markers=("因为", "所以"), level=2, core=True, also_in=(34,)),
    _S("youyu", 15, "由于……(所以)…… — owing to", "由于下大雨，巴士迟到了。",
       "Give a reason in a more formal way.",
       notes=_CONJ + "Formal / news style; recognise and use in formal contexts.",
       markers=("由于",), level=4),
    _S("yinci", 15, "因此 — therefore", "……，因此……",
       "State a consequence formally.",
       notes="Formal 'therefore', starting the second clause: 他生病了，因此没来.",
       markers=("因此",), level=4, also_in=(31,)),
    _S("suoyi", 15, "所以 — so", "……，所以……",
       "Say what follows from something.",
       notes="Very common on its own in speech: 下雨了，所以我不去了.",
       markers=("所以",), level=1),
    _S("yinwei_er", 15, "因为……而…… — because of (written)", "他因为生病而没来。",
       "Recognise a formal way of linking cause and result.",
       notes="Written/formal register; mostly for recognition.",
       markers=("而",), level=5),

    # 15. Conjunctions — condition
    _S("ruguo_jiu", 15, "如果……(的话)，就…… — if … then …", "如果下雨，我就不去。",
       "Say what happens if something is true.",
       notes=_CONJ + "的话 optional at the end of the if-clause. 就 before the verb "
             "of the result.",
       markers=("如果",), level=2, core=True, also_in=(27, 33, 34)),
    _S("yaoshi_jiu", 15, "要是……就…… — if (spoken)", "要是你有空，就来玩。",
       "Say 'if' the everyday spoken way.",
       notes=_CONJ + "Colloquial equivalent of 如果; 要是……的话 also common.",
       markers=("要是",), level=3, also_in=(33, 35)),
    _S("yao_jiu", 15, "要……就…… — if you want to …, then …", "要去就快点。/ 要吃就吃吧。",
       "Say 'if you're going to (or want to) do it, then …'.",
       notes=_CONJ + "要 = want / intend: 要走就走 / 要买就买这个.",
       markers=("要",), level=3, also_in=(35,)),
    _S("zhiyao_jiu", 15, "只要……就…… — as long as", "只要有时间，我就去。",
       "Say that one condition is enough.",
       notes=_CONJ + "Easy / sufficient condition. Contrast 只有……才…… (the only way).",
       contrast=("zhiyou_cai",), markers=("只要",), level=3, core=True,
       also_in=(27, 33, 34)),
    _S("zhiyou_cai", 15, "只有……才…… — only if", "只有多讲，才会进步。",
       "Say that something happens only under one condition.",
       notes=_CONJ + "Strict / necessary condition. Contrast 只要……就…….",
       contrast=("zhiyao_jiu",), markers=("只有",), level=3, core=True,
       also_in=(17, 18, 27, 33, 34)),
    _S("chufei_cai", 15, "除非……才…… — only if, not unless", "除非你去，我才去。",
       "Say something will only happen under one condition.",
       notes=_CONJ + "Strongly restrictive; close to 只有……才…….",
       markers=("除非",), level=4, also_in=(18, 33)),
    _S("chufei_fouze", 15, "除非……否则…… — unless … otherwise", "除非下雨，否则我们都去。",
       "Say what will happen unless a condition is met.",
       notes=_CONJ + "否则 = otherwise; 不然 is the spoken version.",
       markers=("除非",), level=4, also_in=(27, 33)),
    _S("jiaru", 15, "假如……就…… — supposing", "假如你是我，你会怎么做？",
       "Set up a hypothetical.",
       notes=_CONJ + "Slightly formal; hypothetical situations.",
       markers=("假如",), level=4, also_in=(33,)),
    _S("jiashi", 15, "假使……就…… — if (literary)", "假使明天下雨，就改天去。",
       "Recognise a literary 'if'.",
       notes=_CONJ + "Rare in speech; recognition only.",
       markers=("假使",), level=5),

    # 15. Conjunctions — concession
    _S("suiran_danshi", 15, "虽然……但是 / 可是…… — although", "虽然很贵，但是很好吃。",
       "Admit one thing but say another is true anyway.",
       notes=_CONJ + "Unlike English, both halves are used. 可是 is the same, a little "
             "more spoken.",
       markers=("虽然",), level=2, core=True, also_in=(34,)),
    _S("jishi_ye", 15, "即使……也…… — even if", "即使下雨，我也去。",
       "Say something holds even in a hypothetical case.",
       notes=_CONJ + "Hypothetical (unlike 虽然, which states a fact).",
       markers=("即使",), level=3, core=True, also_in=(33, 34)),
    _S("napa_ye", 15, "哪怕……也…… — even if (emphatic)", "哪怕很累，我也要去。",
       "Say you'll do it even in an extreme case.",
       notes=_CONJ + "Stronger, spoken; often with determination.",
       markers=("哪怕",), level=4, also_in=(33,)),
    _S("jiusuan_ye", 15, "就算……也…… — even if (spoken)", "就算你不来，我也去。",
       "Say 'even if' the everyday way.",
       notes=_CONJ + "Very common in speech; same meaning as 即使.",
       markers=("就算",), level=3, also_in=(33,)),
    _S("wulun_dou", 15, "无论 / 不论……都…… — no matter", "无论多忙，他都来。",
       "Say something holds whatever the circumstances.",
       notes=_CONJ + "Needs a question word or options after 无论: 无论什么时候 / 无论"
             "你去不去 / 无论下雨还是晴天. 不论 is the same.",
       markers=("无论", "不论"), level=3, core=True, also_in=(33, 34)),
    _S("buguan_dou", 15, "不管……都…… — no matter (spoken)", "不管你说什么，我都不去。",
       "Say 'no matter' the everyday way.",
       notes=_CONJ + "Same as 无论, more spoken; also needs a question word or "
             "options.",
       markers=("不管",), level=3, also_in=(33,)),

    # 15. Conjunctions — sequence / addition / choice / contrast / inference
    _S("yi_jiu", 15, "一……就…… — as soon as / whenever", "我一到家就睡觉。",
       "Say one thing happens immediately after (or whenever) another does.",
       notes=_CONJ + "一 and 就 each before a verb: 他一喝咖啡就睡不着. 一……便…… is "
             "the literary version.",
       markers=("一",), level=2, core=True, also_in=(16, 19, 27, 34)),
    _S("jiezhe", 15, "接着 — next, then carry on", "……，接着……",
       "Say what came next, continuing on.",
       notes="我们先去巴刹，接着去银行 / 你接着说.",
       markers=("接着",), level=3),
    _S("budan_erqie", 15, "不但……而且…… — not only … but also", "这家不但便宜，而且好吃。",
       "Add a second, stronger point.",
       notes=_CONJ + "Same subject: 他不但会讲华语，而且会讲福建话.",
       markers=("不但",), level=3, core=True, also_in=(34,)),
    _S("bujin_hai", 15, "不仅 / 不但……还…… — not only … also", "他不仅会做菜，还会做面包。",
       "Add a further point, spoken style.",
       notes=_CONJ + "还 before the second verb.",
       markers=("不仅", "不但"), level=3, also_in=(34,)),
    _S("you_you", 15, "又……又…… — both … and …", "又便宜又好吃 / 又累又饿",
       "Say something has two qualities at once.",
       notes="Adjectives or verbs of the same kind (both good or both bad).",
       markers=("又",), level=2, also_in=(16, 19, 34)),
    _S("ji_you", 15, "既……又…… — both … and (formal)", "他既聪明又努力。",
       "Say something has two qualities, more formally.",
       notes="Written or careful speech.",
       markers=("既",), level=4, also_in=(34,)),
    _S("chule_hai", 15, "除了……以外，还 / 也…… — besides … also", "除了华语以外，他还会讲福建话。",
       "Add something on top of what you've mentioned.",
       notes=_CONJ + "还/也 = in addition (inclusive). Contrast 除了……都 (except).",
       contrast=("chule_dou",), markers=("除了",), level=3, core=True,
       also_in=(18, 23, 34)),
    _S("haishi_or", 15, "还是 — or (in questions)", "你要咖啡还是茶？",
       "Offer a choice in a question.",
       notes="Questions only; statements use 或者.",
       contrast=("huozhe",), markers=("还是",), level=1),
    _S("huozhe", 15, "或者 — or (in statements)", "拜六或者礼拜天都可以。",
       "Give alternatives in a statement.",
       notes="Also 或者……或者……. Contrast 还是 in questions.",
       contrast=("haishi_or",), markers=("或者",), level=2),
    _S("yaome", 15, "要么……要么…… — either … or", "要么今天去，要么明天去。",
       "Say one of two options must be chosen.",
       notes="Implies no third choice.",
       markers=("要么",), level=4),
    _S("danshi", 15, "但是 / 可是 — but", "……，但是……",
       "Introduce a contrast.",
       notes="可是 is the same, a little more spoken.",
       markers=("但是", "可是"), level=1),
    _S("buguo", 15, "不过 — but, however (softer)", "……，不过……",
       "Add a softer 'but'.",
       notes="Gentler than 但是: 这家很好吃，不过有点贵.",
       markers=("不过",), level=2),
    _S("er_contrast", 15, "而 — while, whereas (formal)", "他喜欢吃辣，而我不能吃辣。",
       "Contrast two parallel facts, formally.",
       notes="Written/formal register.",
       markers=("而",), level=4),
    _S("bushi_ershi", 15, "不是……而是…… — not … but …", "不是我不想去，而是没有时间。",
       "Correct a wrong idea and give the right one.",
       notes=_CONJ + "Spoken often 不是……是…….",
       markers=("不是",), level=3, core=True, also_in=(34,)),
    _S("jiran_jiu", 15, "既然……就 / 那么…… — since (given that)", "既然你来了，就吃饭吧。",
       "Draw a conclusion from something both people accept.",
       notes=_CONJ + "The first half is known and agreed; different from 因为 (giving "
             "a reason).",
       markers=("既然",), level=3, core=True, also_in=(34,)),
    _S("yuanlai", 15, "原来 — it turns out / originally", "原来是你!/ 原来他是老师。",
       "Say you've just realised something (or how it was before).",
       notes="Discovery: 原来是这样! Also 'originally' (我原来住在怡保).",
       markers=("原来",), level=3, also_in=(29, 31)),
    _S("nanguai", 15, "难怪 — no wonder", "难怪他没来，原来他生病了。",
       "Say something now makes sense.",
       notes="Often paired with 原来.",
       markers=("难怪",), level=3, also_in=(29, 31)),
    _S("guoran", 15, "果然 — sure enough", "他说会下雨，果然下雨了。",
       "Say something happened as expected.",
       notes="Confirms a prediction.",
       markers=("果然",), level=4, also_in=(31,)),

    # ------------------------------------------------------------------
    # 16. 就 / 才 / 还 / 又 / 再
    # ------------------------------------------------------------------
    _S("cai_late", 16, "才 — not until, later than expected", "他十点才来。/ 我昨天才知道。",
       "Say something happened later (or took more) than expected.",
       notes=_JIUCAI + "No 了 with this 才 (他十点才来, NOT 才来了).",
       contrast=("jiu_early",), markers=("才",), level=3, core=True, also_in=(17,)),
    _S("jiu_early", 16, "就 — already, early, right away", "他八点就来了。/ 我马上就来。",
       "Say something happened earlier or sooner than expected.",
       notes=_JIUCAI + "Usually with 了 for past events (八点就到了). Also 'then' in "
             "sequences (吃了饭就走).",
       contrast=("cai_late",), markers=("就",), level=3, core=True),
    _S("cai_vs_jiu", 16, "才 vs 就", "他十点才来 ↔ 他八点就来了",
       "Hear whether something was later or earlier than expected.",
       notes=_JIUCAI + "Same time, different attitude: 十点就来了 (early!) vs 十点才来 "
             "(late!).",
       contrast=("cai_late", "jiu_early"), markers=("才", "就"), level=3, core=True,
       kind="contrast", also_in=(30,)),
    _S("you_vs_zai", 16, "又 vs 再 — again", "他又来了 ↔ 他明天再来",
       "Tell 'again (it happened)' from 'again (it will)'.",
       notes="又 = repeated and already happened (or certain); 再 = repetition still "
             "to come.",
       contrast=("you_again", "zai_again"), markers=("又", "再"), level=2, core=True,
       kind="contrast", also_in=(30,)),
    _S("hai_also", 16, "还 — also, in addition", "我还要一杯。/ 还有呢？",
       "Add something more.",
       notes="还要 / 还有 / 还想: 你还要什么？ 还有吗？",
       markers=("还",), level=2, also_in=(18,)),
    _S("hai_vs_you", 16, "还 vs 又", "他又来了 ↔ 他还没来 / 他明天还来",
       "Tell 'again (done)' from 'still / also / again (to come)'.",
       notes="又 for completed repetition; 还 for continuation (还在, 还没) and for "
             "future repetition (明天还来 = will come again).",
       contrast=("hai_still", "you_again"), markers=("还", "又"), level=3, core=True,
       kind="contrast", also_in=(30,)),
    _S("jiu_emphatic", 16, "就 — exactly, just, only", "就是他!/ 就在这里。/ 就一个。",
       "Emphasise: exactly this, right here, only this much.",
       notes="就是 = that's exactly it; 就在 = right (here); 就一个 / 就我一个人 = "
             "only; 我就不去! = I just won't.",
       markers=("就",), level=3),
    _S("cai_only", 16, "才 — only (fewer than expected)", "才十块!/ 他才三岁。",
       "Say an amount is surprisingly small.",
       notes=_JIUCAI + "才 + amount: 才吃了一碗 / 才五分钟.",
       markers=("才",), level=3, also_in=(17,)),
    _S("jiu_vs_cai_cond", 16, "就 vs 才 in conditions", "只要有时间就去 ↔ 只有有时间才去",
       "Tell an easy condition (就) from a strict one (才).",
       notes=_JIUCAI + "只要……就 / 如果……就 = if this, then (easily) that; 只有……才 / "
             "除非……才 = only this way.",
       contrast=("zhiyao_jiu", "zhiyou_cai"), markers=("就", "才"), level=4, core=True,
       kind="contrast", also_in=(30,)),

    # ------------------------------------------------------------------
    # 17. Focus, emphasis & limitation
    # ------------------------------------------------------------------
    _S("lian_dou", 17, "连……都 / 也…… — even", "连他都知道。/ 他连饭都没吃。",
       "Stress an extreme case: even this.",
       notes="连 + the surprising item + 都/也 + verb.",
       markers=("连",), level=3, core=True),
    _S("shenzhi", 17, "甚至 — even (going further)", "他很忙，甚至没时间吃饭。",
       "Add a more extreme point.",
       notes="Often with 都/也 after the point.",
       markers=("甚至",), level=4, also_in=(18, 31)),
    _S("zhi_only", 17, "只 / 只有 — only", "我只喝水。/ 只有他知道。/ 我只有十块。",
       "Limit something to one thing, person or amount.",
       notes="只 before the verb (只喝水); 只有 + person = only they (只有他知道); 只有 "
             "+ amount = only have.",
       markers=("只",), level=2, also_in=(18,)),
    _S("guang_jiu", 17, "光……就…… — just … alone", "光车费就要五十块。",
       "Say one part alone is already a lot.",
       notes="光 / 光是 + part + 就 + amount.",
       markers=("光",), level=4),
    _S("hai_surprise", 17, "还……呢 — even (surprise)", "他还会讲福建话呢!",
       "Mention a surprising extra.",
       notes="还 + verb, often with 呢: 这里还有榴莲卖呢!",
       markers=("还",), level=4),
    _S("lian_dou_meiyou", 17, "连……都没(有)…… — not even", "我连一块钱都没有。",
       "Say not even the smallest thing happened or exists.",
       notes="连一句话都没说 / 连饭都没吃.",
       markers=("连",), level=3),
    _S("qword_dou", 17, "Question word + 都 — every-, any-", "什么都吃 / 谁都认识他 / 哪里都可以 / 怎么都行",
       "Say everything, everyone, everywhere, any way.",
       notes="Positive meanings (negatives are earlier structures). Malaysian 哪里都, "
             "never 哪儿.",
       markers=("都", "也"), level=3),
    _S("dou_meanings", 17, "都 — all / even / already", "我们都去 · 连他都知道 · 都十点了!",
       "Hear which meaning of 都 is meant.",
       notes="All (refers back to plural before it); even (with 连); already (都 + "
             "time + 了, often impatient).",
       markers=("都",), level=3, also_in=(18,)),

    # ------------------------------------------------------------------
    # 18. Addition, exclusion & scope
    # ------------------------------------------------------------------
    _S("chule_dou", 18, "除了……以外，都 / 没…… — except", "除了他以外，我们都去。",
       "Say everyone or everything except one.",
       notes="都 / 没 = excluding (除了他以外，没有人知道). Contrast 除了……还 (besides).",
       contrast=("chule_hai",), markers=("除了",), level=3),
    _S("ye_also", 18, "也 — also, too", "我也去。/ 他也不知道。",
       "Say 'too' or 'also'.",
       notes="Before the verb, never at the end (NOT 我去也). With negation: 也不 / "
             "也没.",
       markers=("也",), level=1),

    # ------------------------------------------------------------------
    # 19. Simultaneous & related actions
    # ------------------------------------------------------------------
    _S("yibian", 19, "一边……一边…… — while", "他一边吃饭一边看手机。",
       "Say two activities happen at the same time.",
       notes="Short form 边……边…… (边吃边聊); formal 一面……一面……. Modals go before "
             "the first 一边 (你可以一边听一边写 / 不要一边驾车一边打电话).",
       markers=("边",), level=2, core=True, also_in=(34,)),
    _S("zhe_manner", 19, "Verb + 着 + verb — while in that state", "走着去 / 站着吃 / 笑着说",
       "Say how an action is done: on foot, standing, smiling.",
       notes="The first verb + 着 describes the manner of the second.",
       contrast=("yibian",), markers=("着",), level=3),
    _S("zhe_scene", 19, "Place + verb + 着 + thing — describing a scene", "桌上放着一本书。",
       "Describe what is where.",
       notes="门口站着一个人 / 墙上挂着一张照片.",
       markers=("着",), level=4),
    _S("yibian_vs_zhe", 19, "一边……一边 vs verb + 着", "一边吃一边看 ↔ 站着吃",
       "Tell two parallel activities from the manner of one.",
       notes="一边 = two activities at once; V着 + V = one activity done in a "
             "particular way or posture.",
       contrast=("yibian", "zhe_manner"), level=4, kind="contrast"),

    # ------------------------------------------------------------------
    # 20. Relative clauses & noun modification
    # ------------------------------------------------------------------
    _S("rel_v_de", 20, "Verb phrase + 的 + noun — the … that …", "我买的书 / 昨天来的人",
       "Describe a noun by what someone did or does.",
       notes=_REL + "你说的那家店 / 我昨天买的面包.",
       markers=("的",), level=3, core=True),
    _S("rel_place_de", 20, "Place + 的 + noun", "桌上的书 / 巴刹的菜 / 槟城的朋友",
       "Describe a noun by where it is or comes from.",
       notes=_REL + "Also 在 + place + 的 (在桌子上的书).",
       markers=("的",), level=2),
    _S("rel_time_de", 20, "Time + 的 + noun", "昨天的报纸 / 三点的巴士",
       "Describe a noun by its time.",
       notes=_REL,
       markers=("的",), level=2),
    _S("rel_person", 20, "…… + 的人 — the one who …", "会讲福建话的人 / 昨天来的人是谁？",
       "Describe a person by what they do.",
       notes=_REL,
       markers=("的人",), level=3),
    _S("rel_things", 20, "……的东西 / ……的地方 — things / places that …", "吃的东西 / 好玩的地方",
       "Describe things or places by what they're for.",
       notes=_REL + "要买的东西 / 住的地方 / 吃饭的地方.",
       markers=("的",), level=3),
    _S("rel_meiyou", 20, "没有……的…… — nothing / no one that …", "家里没有吃的。/ 没有他不会做的菜。",
       "Say there's nothing or no one of a certain kind.",
       notes=_REL + "没有 + description + 的 (+ noun).",
       markers=("没有",), level=4),
    _S("rel_multi", 20, "Several descriptions before a noun", "我昨天在巴刹买的那个大榴莲",
       "Stack descriptions before a noun in a natural order.",
       notes=_REL + "Usual order: whose / when / where + verb phrase + 的, then 这/那 + "
             "number + measure word, then a short adjective, then the noun. Keep "
             "examples natural and not too long.",
       markers=("的",), level=4),

    # ------------------------------------------------------------------
    # 21. Location & existence
    # ------------------------------------------------------------------
    _S("zai_place", 21, "在 + place — be at, be in", "他在家。/ 锁匙在桌上。",
       "Say where someone or something is.",
       notes="你在哪里？ / 我在巴刹.",
       markers=("在",), level=1, core=True, also_in=(23,)),
    _S("v_zai_place", 21, "Verb + 在 + place — end up, stay at", "住在槟城 / 坐在这里 / 放在冰厨里",
       "Say where someone stays or something ends up.",
       notes="After verbs of staying and placing: 住, 坐, 站, 放, 停, 写. Contrast 在 + "
             "place + verb (where an activity happens).",
       contrast=("place_before_verb",), markers=("在",), level=2, core=True,
       also_in=(25,)),
    _S("you_noun_place", 21, "有 + something + 在 + place", "有人在外面等你。",
       "Introduce someone or something that is somewhere.",
       notes="有一只猫在车底下 / 有人在敲门.",
       markers=("有",), level=3),
    _S("place_you", 21, "Place + 有 + something", "桌上有一本书。/ 巴刹有很多人。",
       "Say what there is in a place.",
       notes="Place first, no 在 needed at the start.",
       markers=("有",), level=2),
    _S("place_shi", 21, "Place + 是 + something — what's there", "我家旁边是巴刹。",
       "Say what occupies a place.",
       notes="Identifies what is there: 左边是银行，右边是药房.",
       markers=("是",), level=3),
    _S("zai_you_shi", 21, "在 vs 有 vs 是 for location", "锁匙在桌上 · 桌上有锁匙 · 桌上是锁匙",
       "Choose how to talk about where things are.",
       notes="在: where a known thing is. 有: what exists there (new information). 是: "
             "what occupies it (identifying).",
       contrast=("zai_place", "place_you", "place_shi"), level=3, kind="contrast",
       also_in=(30,)),
    _S("loc_words_1", 21, "上 / 下 / 里 / 外 / 前 / 后", "桌上 / 冰厨里 / 车底下 / 门外 / 屋子后面",
       "Say on, under, in, outside, in front of, behind.",
       notes="Noun + place word (桌子上, 冰厨里); with 在 (在桌子上). 前面 / 后面 / 外"
             "面 / 里面 stand alone.",
       markers=("上", "下", "里", "外", "前", "后"), level=2, core=True),
    _S("loc_words_2", 21, "左边 / 右边 / 旁边 / 中间 / 附近", "银行旁边 / 两家店中间 / 我家附近",
       "Say left, right, beside, between, nearby.",
       notes="Noun + place word: 巴刹旁边, 学校附近.",
       markers=("左", "右", "旁边", "中间", "附近"), level=2),
    _S("li_distance", 21, "A 离 B 近 / 远", "我家离巴刹很近。",
       "Say how near or far one place is from another.",
       notes="离这里远吗？ / 离槟城不远.",
       markers=("离",), level=2),
    _S("wang_toward", 21, "往 + direction + verb — head towards", "往前走 / 往左转 / 往那边去",
       "Give directions: go this way.",
       notes="Directions to drivers and walkers.",
       markers=("往",), level=2, also_in=(22, 23)),
    _S("xiang_toward", 21, "向 + direction / person — towards, from", "向前看 / 向右转 / 向他学习",
       "Say towards a direction, or learn from / greet a person.",
       notes="向他学习, 向老师问好. More formal than 往 for directions.",
       markers=("向",), level=3, also_in=(23,)),
    _S("chao_toward", 21, "朝 + direction — facing, towards", "朝南的房子 / 他朝我走过来",
       "Say which way something faces or moves.",
       notes="Facing (朝南) or moving towards (朝我走来).",
       markers=("朝",), level=4, also_in=(23,)),
    _S("dao_place", 21, "到 + place — arrive, get to", "我到了。/ 到巴刹要多久？",
       "Say you've arrived or how to get somewhere.",
       notes="到了打电话给我 / 几点到？",
       markers=("到",), level=1, also_in=(23,)),
    _S("cong_from", 21, "从 + place — from", "我从怡保来。/ 从这里走。",
       "Say where from.",
       notes="从 + place + verb.",
       markers=("从",), level=1, also_in=(23,)),
    _S("dui_toward", 21, "对 + person — to, towards, for", "他对我很好。/ 对身体不好。",
       "Say how someone treats, or what is good or bad for, someone.",
       notes="对 + person + adjective / attitude; 对……有兴趣.",
       markers=("对",), level=2, also_in=(23, 24)),

    # ------------------------------------------------------------------
    # 22. Direction, movement & path
    # ------------------------------------------------------------------
    _S("lai_qu", 22, "来 / 去 — come or go", "你来我家吧。/ 我去你家。",
       "Choose come or go depending on where the speaker is.",
       notes="来 = towards the speaker's location; 去 = away. Phone and invitations: "
             "来我家玩 / 我明天去你那里.",
       markers=("来", "去"), level=1, core=True),
    _S("dao_lai_qu", 22, "到……来 / 到……去", "到我家来 / 到外面去",
       "Say come to or go to a place.",
       notes="Same as 来我家 / 去外面, a little fuller.",
       markers=("到",), level=2),
    _S("cong_lai", 22, "从……来 — come from", "你从哪里来？",
       "Say where someone comes from.",
       notes="他从新加坡来 / 你是从哪里来的？",
       markers=("从",), level=1),
    _S("jin_chu", 22, "进 / 出 — go in, go out", "进房间 / 出门 / 进来",
       "Say go in or go out.",
       notes="进 + place / 出 + place.",
       markers=("进", "出"), level=1),
    _S("shang_xia_move", 22, "上 / 下 — get on, go up / down", "上车 / 下车 / 上楼 / 下楼",
       "Say get on or off, go up or down.",
       notes="上巴士 / 下车 / 上班 is a separate word.",
       markers=("上", "下"), level=1),
    _S("hui_return", 22, "回 + place — go back to", "回家 / 回怡保 / 回公司",
       "Say go back somewhere.",
       notes="几点回家？",
       markers=("回",), level=1),
    _S("guo_cross", 22, "过 + place — cross, go past", "过马路 / 过桥 / 过了银行就到",
       "Say cross or go past something.",
       notes="Directions: 过了红绿灯往左转.",
       markers=("过",), level=2),
    _S("likai", 22, "离开 — leave", "离开家 / 离开马来西亚",
       "Say leave a place or person.",
       notes="他已经离开了.",
       markers=("离开",), level=2),
    _S("zou_dao", 22, "走到 + place — walk (up) to", "走到门口 / 走到巴刹要十分钟",
       "Say walk as far as somewhere.",
       notes="Also 跑到, 开到.",
       markers=("到",), level=2),
    _S("zou_jin", 22, "走进 + place — walk into", "他走进房间。",
       "Say walk into somewhere.",
       notes="走进来 / 走进去.",
       markers=("进",), level=3),
    _S("zou_chulai", 22, "走出(来 / 去) — walk out", "他从房间走出来。",
       "Say walk out of somewhere.",
       notes="走出来 (towards speaker) / 走出去 (away).",
       markers=("出",), level=3),
    _S("carry_in_out", 22, "拿 / 带 + 进去 / 出来 — take in, bring out", "把椅子拿进去 / 带孩子出来",
       "Say take something in or bring it out.",
       notes="Often with 把.",
       markers=("进去", "出来", "进来", "出去"), level=3),
    _S("dai_lai_qu", 22, "带来 / 带去 — bring, take along", "你带来了吗？/ 带去给他",
       "Say bring or take along.",
       notes="带 + thing/person + 来/去: 带水来 / 带孩子去.",
       markers=("带",), level=2),
    _S("move_place", 22, "Movement verb + place", "跑回家 / 飞到槟城 / 搬到怡保",
       "Say where a movement ends.",
       notes="Verb + 到 / 回 / 进 + place.",
       markers=("到", "回", "进"), level=3),
    _S("dir_vs_prep", 22, "Moving somewhere vs acting in a place", "走进房间 ↔ 在房间里走",
       "Tell where a movement ends from where an activity happens.",
       notes="跑到公园 (end up at the park) vs 在公园跑 (run in the park).",
       contrast=("dir_simple", "place_before_verb"), level=4, kind="contrast",
       also_in=(30,)),
]

LISTED = {
    15: [
        ("因为……所以……", "yinwei_suoyi"),
        ("由于……所以……", "youyu"),
        ("因此……", "yinci"),
        ("所以……", "suoyi"),
        ("因为……而……", "yinwei_er"),
        ("如果……就……", "ruguo_jiu"),
        ("要是……就……", "yaoshi_jiu"),
        ("要……就……", "yao_jiu"),
        ("只要……就……", "zhiyao_jiu"),
        ("只有……才……", "zhiyou_cai"),
        ("除非……才……", "chufei_cai"),
        ("除非……否则……", "chufei_fouze"),
        ("假如……就……", "jiaru"),
        ("假使……就……", "jiashi"),
        ("虽然……但是……", "suiran_danshi"),
        ("虽然……可是……", "suiran_danshi"),
        ("即使……也……", "jishi_ye"),
        ("哪怕……也……", "napa_ye"),
        ("就算……也……", "jiusuan_ye"),
        ("无论……都……", "wulun_dou"),
        ("不管……都……", "buguan_dou"),
        ("不论……都……", "wulun_dou"),
        ("一……就……", "yi_jiu"),
        ("一……便……", "yi_jiu"),
        ("先……再……", "xian_zai"),
        ("然后……", "ranhou"),
        ("接着……", "jiezhe"),
        ("最后……", "zuihou"),
        ("不但……而且……", "budan_erqie"),
        ("不仅……还……", "bujin_hai"),
        ("不但……还……", "bujin_hai"),
        ("又……又……", "you_you"),
        ("既……又……", "ji_you"),
        ("除了……以外，还……", "chule_hai"),
        ("还是……", "haishi_or"),
        ("或者……", "huozhe"),
        ("或者……或者……", "huozhe"),
        ("要么……要么……", "yaome"),
        ("但是……", "danshi"),
        ("可是……", "danshi"),
        ("不过……", "buguo"),
        ("而……", "er_contrast"),
        ("而是……", "bushi_ershi"),
        ("不是……而是……", "bushi_ershi"),
        ("既然……就……", "jiran_jiu"),
        ("既然……那么……", "jiran_jiu"),
        ("原来……", "yuanlai"),
        ("难怪……", "nanguai"),
        ("果然……", "guoran"),
    ],
    16: [
        ("一……就……", "yi_jiu"),
        ("才 — only then / not until / late", "cai_late"),
        ("就 — then / already / soon / only", "jiu_early"),
        ("才 vs 就", "cai_vs_jiu"),
        ("又 — again (completed/present/repeated)", "you_again"),
        ("再 — again (future/additional)", "zai_again"),
        ("又 vs 再", "you_vs_zai"),
        ("还 — still", "hai_still"),
        ("又……又……", "you_you"),
        ("还…… — also/still", "hai_also"),
        ("还 vs 又", "hai_vs_you"),
        ("就…… — immediate/early/emphatic", "jiu_emphatic"),
        ("才…… — delayed/limited", "cai_only"),
        ("就 vs 才 in conditional sentences", "jiu_vs_cai_cond"),
    ],
    17: [
        ("是……的", "shi_de"),
        ("连……都/也……", "lian_dou"),
        ("甚至…… — even", "shenzhi"),
        ("只…… — only", "zhi_only"),
        ("只有……才……", "zhiyou_cai"),
        ("才…… — only/not until", "cai_only"),
        ("光……就…… — merely/just", "guang_jiu"),
        ("还…… — even/still", "hai_surprise"),
        ("连……都没有……", "lian_dou_meiyou"),
        ("什么都……", "qword_dou"),
        ("谁都……", "qword_dou"),
        ("哪儿都……", "qword_dou"),
        ("怎么都……", "qword_dou"),
        ("一点都……", "yidian_bu"),
        ("一点也……", "yidian_bu"),
        ("都 — all / even / already depending on context", "dou_meanings"),
    ],
    18: [
        ("除了 A 以外，其他都……", "chule_dou"),
        ("除了 A 以外，还有 B", "chule_hai"),
        ("除了 A 以外，也……", "chule_hai"),
        ("除了 A 以外，没……", "chule_dou"),
        ("除非……", "chufei_cai"),
        ("只有……", "zhi_only"),
        ("只……", "zhi_only"),
        ("都……", "dou_meanings"),
        ("也……", "ye_also"),
        ("还……", "hai_also"),
        ("甚至……", "shenzhi"),
    ],
    19: [
        ("一边……一边……", "yibian"),
        ("一面……一面……", "yibian"),
        ("又……又……", "you_you"),
        ("边……边……", "yibian"),
        ("V 着 + V", "zhe_manner"),
        ("V 着 + location", "zhe_scene"),
        ("一边……一边…… vs V 着……", "yibian_vs_zhe"),
        ("一……就……", "yi_jiu"),
        ("一边……一边…… + modal verbs", "yibian"),
    ],
    20: [
        ("V + 的 + noun", "rel_v_de"),
        ("Adjective + 的 + noun", "adj_de_noun"),
        ("Possessive + 的 + noun", "de_possessive"),
        ("Place + 的 + noun", "rel_place_de"),
        ("Time + 的 + noun", "rel_time_de"),
        ("谁 + V + 的人", "rel_person"),
        ("我买的书", "rel_v_de"),
        ("在桌子上的书", "rel_place_de"),
        ("昨天买的书", "rel_v_de"),
        ("没有……的……", "rel_meiyou"),
        ("的 nominalisation", "de_nominal"),
        ("……的东西", "rel_things"),
        ("……的人", "rel_person"),
        ("……的地方", "rel_things"),
        ("……的时候", "de_shihou"),
        ("Multiple modifiers before noun", "rel_multi"),
        ("Modifier ordering", "rel_multi"),
    ],
    21: [
        ("在 + place", "zai_place"),
        ("V + 在 + place", "v_zai_place"),
        ("有 + noun + place", "you_noun_place"),
        ("Place + 有 + noun", "place_you"),
        ("是 + place", "place_shi"),
        ("在 vs 有 vs 是", "zai_you_shi"),
        ("上 / 下 / 里 / 外 / 前 / 后", "loc_words_1"),
        ("左 / 右 / 旁边 / 中间 / 附近", "loc_words_2"),
        ("离……近/远", "li_distance"),
        ("从……到……", "cong_dao"),
        ("往…… — toward", "wang_toward"),
        ("向…… — toward", "xiang_toward"),
        ("朝…… — toward", "chao_toward"),
        ("在……上/下/里/外", "loc_words_1"),
        ("到…… — arrive/go to", "dao_place"),
        ("从…… — from", "cong_from"),
        ("对…… — toward/with respect to", "dui_toward"),
    ],
    22: [
        ("来 / 去", "lai_qu"),
        ("到……去", "dao_lai_qu"),
        ("到……来", "dao_lai_qu"),
        ("从……来", "cong_lai"),
        ("往……去", "wang_toward"),
        ("往……来", "wang_toward"),
        ("进 / 出", "jin_chu"),
        ("上 / 下", "shang_xia_move"),
        ("回", "hui_return"),
        ("过", "guo_cross"),
        ("离开", "likai"),
        ("走到……", "zou_dao"),
        ("走进……", "zou_jin"),
        ("走出来……", "zou_chulai"),
        ("拿进去 / 拿出来", "carry_in_out"),
        ("带来 / 带去", "dai_lai_qu"),
        ("带进去 / 带出来", "carry_in_out"),
        ("Movement verb + location", "move_place"),
        ("Directional complement vs preposition", "dir_vs_prep"),
    ],
}
