# src/grammar_data_3.py
"""Grammar curriculum, groups 9-14: complements, 把, 被, 是……的, comparison,
adverbials."""

from grammar_schema import Structure

SECTIONS = {
    9: "Complement System",
    10: "把 Construction",
    11: "Passive Constructions",
    12: "是……的 Construction",
    13: "Comparison",
    14: "Adverbial Structures",
}

_S = Structure
_RC = ("Teach the result the complement adds, by meaning (finished / found / "
       "understood / gone), never by terminology. Negate with 没 (没吃完); 了 goes "
       "after the complement (吃完了, NOT 吃了完). ")
_POT = ("得/不 go between the verb and its result: 吃得完 = can finish, 吃不完 = "
        "can't finish (too much). It says whether the result can be achieved. ")
_BA = ("把 moves a specific, known object before the verb to say what happens to "
       "it. The verb can never stand alone after 把 + object: it needs a result, "
       "direction, place, 了, 一下 or a doubled verb (NOT 把书看). ")
_BEI = ("被 + (doer) + verb + something: the verb can't stand alone (needs a "
        "result, direction or 了). 被 mostly reports unwelcome events. ")

STRUCTURES = [
    # ------------------------------------------------------------------
    # 9A. Resultative complements
    # ------------------------------------------------------------------
    _S("res_wan", 9, "Verb + 完 — finish", "吃完 / 做完 / 看完",
       "Say you've finished doing something.",
       notes=_RC + "吃完了 / 这本书我看完了 / 你做完了吗？",
       markers=("完",), level=2, core=True),
    _S("res_hao", 9, "Verb + 好 — done properly, ready", "做好 / 准备好 / 坐好",
       "Say something is done properly and ready.",
       notes=_RC + "饭做好了 / 准备好了吗？/ 穿好衣服 / 坐好 (sit properly).",
       markers=("好",), level=2, core=True),
    _S("res_dao", 9, "Verb + 到 — manage to, reach", "找到 / 买到 / 看到 / 收到 / 走到",
       "Say you managed to get, find, see or reach something.",
       notes=_RC + "找到了锁匙 / 买到了 / 收到你的短讯 / 走到巴刹 / 等到十点 (until). "
             "看到 is the everyday Malaysian 'see'.",
       markers=("到",), level=2, core=True),
    _S("res_jian", 9, "Verb + 见 — perceive", "看见 / 听见 / 遇见",
       "Say you saw or heard something (it registered).",
       notes=_RC + "看见 / 听见 = saw / heard (the result). Malaysians often say 看到 / "
             "听到; recognise both.",
       markers=("见",), level=2),
    _S("res_dong", 9, "Verb + 懂 — understand", "听懂 / 看懂",
       "Say you understood what you heard or read.",
       notes=_RC + "听懂了 / 你看懂了吗？/ 我没听懂.",
       markers=("懂",), level=2, core=True),
    _S("res_qingchu", 9, "Verb + 清楚 — clearly", "看清楚 / 听清楚 / 讲清楚",
       "Say something was seen, heard or explained clearly.",
       notes=_RC + "请讲清楚一点 / 我没听清楚 / 看清楚了吗？",
       markers=("清楚",), level=3),
    _S("res_cuo", 9, "Verb + 错 — get it wrong", "听错 / 说错 / 走错 / 拿错",
       "Say something was done wrongly: misheard, took the wrong one.",
       notes=_RC + "我听错了 / 你拿错了 / 走错路了.",
       contrast=("res_dui",), markers=("错",), level=2),
    _S("res_dui", 9, "Verb + 对 — get it right", "说对 / 猜对 / 做对",
       "Say something was done correctly.",
       notes=_RC + "你猜对了 / 这题做对了.",
       contrast=("res_cuo",), markers=("对",), level=3),
    _S("res_kai", 9, "Verb + 开 — open, away, apart", "打开 / 走开 / 分开 / 拉开",
       "Say something is opened up, moved away or separated.",
       notes=_RC + "打开窗口 / 走开! / 把两个分开.",
       markers=("开",), level=3),
    _S("res_guang", 9, "Verb + 光 — all used up", "吃光 / 用光 / 卖光 / 花光",
       "Say something is completely used up or gone.",
       notes=_RC + "饭吃光了 / 钱花光了 / 榴莲卖光了.",
       markers=("光",), level=3),
    _S("res_zhu", 9, "Verb + 住 — hold firm, fix in place", "记住 / 抓住 / 站住 / 停住",
       "Say something is held, fixed or remembered firmly.",
       notes=_RC + "记住了吗？/ 抓住! / 站住!",
       markers=("住",), level=3),
    _S("res_cheng", 9, "Verb + 成 — turn into, (mis)take as", "变成 / 听成 / 看成 / 换成",
       "Say something turned into, or was taken as, something else.",
       notes=_RC + "我听成四点五十了 / 把美金换成令吉 / 冰变成水.",
       markers=("成",), level=3),
    _S("res_zou", 9, "Verb + 走 — take away", "拿走 / 带走 / 偷走 / 搬走",
       "Say something was taken or carried away.",
       notes=_RC + "谁拿走了我的伞？/ 他们搬走了.",
       markers=("走",), level=3),
    _S("res_diao", 9, "Verb + 掉 — get rid of, off, gone", "丢掉 / 吃掉 / 关掉 / 忘掉",
       "Say something is got rid of, switched off or gone.",
       notes=_RC + "Malaysian 丢掉 (throw away), 把冷气关掉, 忘掉他吧.",
       markers=("掉",), level=3),
    _S("res_negation", 9, "Negating a result — 没 + verb + result", "没听懂 / 没找到 / 没吃完",
       "Say the action happened but the result wasn't achieved.",
       notes=_RC + "没 + V + result. 不 + V + result only in conditions (不吃完不能走). "
             "Keep apart from 听不懂 (can't understand).",
       contrast=("pot_bu",), markers=("没",), level=2, core=True),
    _S("res_le", 9, "Result + 了", "吃完了 / 找到了 / 听懂了",
       "Report that the result has been achieved.",
       notes=_RC,
       markers=("了",), level=2),
    _S("res_guo", 9, "Result + 过 — ever achieved", "我从来没看到过 / 没吃完过",
       "Say whether a result has ever been achieved.",
       notes=_RC + "Mostly with 没 or 从来没: 我从来没看到过这么大的榴莲.",
       markers=("过",), level=4),

    # ------------------------------------------------------------------
    # 9B. Potential complements
    # ------------------------------------------------------------------
    _S("pot_de", 9, "Verb + 得 + result — can manage it", "吃得完 / 听得懂 / 来得及",
       "Say a result can be achieved.",
       notes=_POT + "Positive forms are common in questions and replies: 吃得完吗？"
             "——吃得完.",
       contrast=("pot_bu",), markers=("得",), level=3, core=True),
    _S("pot_bu", 9, "Verb + 不 + result — can't manage it", "吃不完 / 听不懂 / 找不到 / 睡不着",
       "Say a result can't be achieved.",
       notes=_POT + "Very common: 听不懂, 找不到, 来不及, 买不到, 睡不着, 看不到.",
       contrast=("pot_de", "res_negation"), markers=("不",), level=2, core=True),
    _S("pot_chi_wan", 9, "吃得完 / 吃不完 — can(’t) finish", "吃得完吗？——吃不完。",
       "Say whether you can finish the food (or anything else).",
       notes=_POT + "Also 做不完, 看不完, 用不完.",
       markers=("得完", "不完"), level=2),
    _S("pot_ting_dong", 9, "听得懂 / 听不懂 — can(’t) understand", "你听得懂吗？——听不懂。",
       "Say whether you can understand what's said.",
       notes=_POT + "Also 看得懂 / 看不懂 for reading.",
       markers=("得懂", "不懂"), level=2),
    _S("pot_kan_jian", 9, "看得到 / 看不到 — can(’t) see", "看不到 / 看得见 / 听不到",
       "Say whether you can see or hear something.",
       notes=_POT + "Malaysians mostly say 看得到 / 看不到, 听不到; 看得见 / 看不见 is "
             "the standard form - recognise both.",
       markers=("看得", "看不", "听得", "听不"), level=2),
    _S("pot_zuo_dao", 9, "做得到 / 做不到 — can(’t) do it", "你做得到吗？——我做不到。",
       "Say whether something is achievable.",
       notes=_POT + "Also 办得到 / 办不到, 找得到 / 找不到.",
       markers=("得到", "不到"), level=3),
    _S("pot_question", 9, "Asking with 得 / 不", "听得懂吗？/ 听不听得懂？/ 吃得完吃不完？",
       "Ask whether a result can be achieved.",
       notes=_POT + "Either V得R吗？ or V得R V不R？ (and the spoken 听不听得懂？).",
       markers=("得",), level=3),
    _S("pot_vs_neng", 9, "Can't manage vs not allowed", "我看不到 ↔ 我不能看",
       "Tell 'unable to achieve it' from 'mustn't / not able to do it'.",
       notes=_POT + "看不到 = can't see (too far, too dark); 不能看 = not allowed / "
             "shouldn't. 吃不完 = too much; 不能吃 = not allowed (or it's inedible).",
       contrast=("pot_bu", "neng"), markers=("不",), level=3, kind="contrast"),

    # ------------------------------------------------------------------
    # 9C. Degree complements
    # ------------------------------------------------------------------
    _S("deg_de", 9, "Verb + 得 + adjective — how well", "跑得快 / 做得好 / 讲得不错",
       "Say how well or how fast something is (typically) done.",
       notes="Comments on the manner/result of an action. With an object repeat "
             "the verb (他讲华语讲得很好) or front the object (他华语讲得很好).",
       contrast=("de_manner",), markers=("得",), level=2),
    _S("deg_de_hen", 9, "Verb + 得 + 很 / 不 / 太 + adjective", "说得很好 / 写得不好 / 吃得太快",
       "Add degree or negation to how something is done.",
       notes="The adjective after 得 takes 很/太/不/非常; negation goes after 得 (说得"
             "不好, NOT 不说得好). Question: 说得好不好？",
       markers=("得",), level=2),
    _S("deg_de_clause", 9, "……得 + result — so … that …", "累得走不动 / 忙得没时间吃饭",
       "Say something happened to such a degree that there was a result.",
       notes="Adjective or verb + 得 + clause: 高兴得跳起来, 笑得肚子痛, 热得睡不着.",
       markers=("得",), level=3),
    _S("deg_budeliao", 9, "Adjective + 得不得了 — terribly", "热得不得了 / 高兴得不得了",
       "Say something is extremely so.",
       notes="Emphatic, spoken: 贵得不得了, 累得不得了.",
       markers=("不得了",), level=3, also_in=(13,)),
    _S("deg_dehen", 9, "Adjective + 得很 — very (emphatic)", "好得很 / 贵得很",
       "Stress that something is very so.",
       notes="Comes after the adjective: 这里热得很.",
       markers=("得很",), level=3),
    _S("deg_vs_adverbial", 9, "How it was done vs how to do it", "他讲得很慢 ↔ 你慢慢讲",
       "Tell a comment on how something is done from an instruction on how to do it.",
       notes="After the verb with 得 = judging how it is/was done (他讲得很慢); before "
             "the verb (often doubled, with 地) = the manner intended or asked for (你"
             "慢慢讲, 认真地做).",
       contrast=("deg_de", "de_manner"), level=3, kind="contrast"),

    # ------------------------------------------------------------------
    # 9D. Directional complements
    # ------------------------------------------------------------------
    _S("dir_lai_qu", 9, "Verb + 来 / 去 — towards or away from you", "拿来 / 带去 / 寄来 / 送去",
       "Show whether something moves towards the speaker (来) or away (去).",
       notes="来 = towards where the speaker is; 去 = away from it. On the phone, "
             "'come' and 'go' follow where the speaker is.",
       markers=("来", "去"), level=2, core=True),
    _S("dir_simple", 9, "Verb + 上 / 下 / 进 / 出 / 回 / 过", "走进 / 跑出 / 爬上 / 坐下 / 拿回 / 走过",
       "Show the direction of a movement.",
       notes="Usually followed by a place: 走进房间, 爬上山, 走过马路, 坐下.",
       markers=("上", "下", "进", "出", "回", "过"), level=3),
    _S("dir_compound", 9, "Verb + direction + 来 / 去", "走进来 / 跑出去 / 拿回来 / 站起来",
       "Combine the direction of a movement with towards or away from you.",
       notes="进来 / 出去 / 回来 / 上去 / 下来 / 过来 / 起来 after the main verb.",
       markers=("来", "去"), level=3, core=True),
    _S("dir_shang", 9, "上来 / 上去 — up here, up there", "你上来吧 / 我上去找你",
       "Say someone comes up (to you) or goes up (away from you).",
       notes="Depends on where the speaker is: upstairs speaker says 上来.",
       markers=("上来", "上去"), level=2),
    _S("dir_xia", 9, "下来 / 下去 — down here, down there", "你下来 / 他下去了",
       "Say someone comes down (to you) or goes down (away).",
       notes="Literal movement only here; the 'continue' meaning of 下去 is its "
             "own structure.",
       markers=("下来", "下去"), level=2),
    _S("dir_jin", 9, "进来 / 进去 — come in, go in", "请进来 / 我进去看看",
       "Say someone comes in or goes in.",
       notes="进来 = towards the speaker inside; 进去 = in, away from the speaker.",
       markers=("进来", "进去"), level=2),
    _S("dir_chu", 9, "出来 / 出去 — come out, go out", "你出来一下 / 我们出去吃",
       "Say someone comes out or goes out.",
       notes="出去 is very common for going out (出去玩, 出去吃饭).",
       markers=("出来", "出去"), level=2),
    _S("dir_hui", 9, "回来 / 回去 — come back, go back", "你几点回来？/ 我要回去了",
       "Say someone comes back (here) or goes back (there).",
       notes="回来 when the speaker is at the place returned to; 回去 when not.",
       markers=("回来", "回去"), level=2),
    _S("dir_guo", 9, "过来 / 过去 — come over, go over", "你过来一下 / 我过去找你",
       "Say someone comes over to you or goes over there.",
       notes="Across a space towards or away from the speaker.",
       markers=("过来", "过去"), level=2),
    _S("dir_na", 9, "拿来 / 拿去 — bring, take", "把书拿来 / 这个你拿去吧",
       "Say whether something is being brought to you or taken away.",
       notes="Also 拿过来 / 拿回去 / 拿出来.",
       markers=("拿",), level=2),
    _S("dir_object", 9, "Objects with direction words", "回家来 / 拿一本书来 / 带了一瓶水去",
       "Put objects in the right place in a movement sentence.",
       notes="A place always goes before 来/去 (进房间来, 回家去, NOT 回来家). A thing "
             "can go before 来/去 or after the whole complement (拿一本书来 / 拿来一本"
             "书).",
       markers=("来", "去"), level=3, core=True),
    _S("dir_extended", 9, "Direction words with other meanings", "站起来 ↔ 想起来 · 走下来 ↔ 写下来",
       "Tell a literal movement from an extended meaning: remember, write down, keep going.",
       notes="想起来 (remember), 看起来 (looks like), 说起来 (come to mention it), 写下"
             "来 (note down), 停下来 (come to a stop), 坚持下去 (keep going), 看出来 "
             "(tell / make out). Pair each with a literal use.",
       markers=("起来", "下来", "下去", "出来"), level=4),

    # ------------------------------------------------------------------
    # 10. 把
    # ------------------------------------------------------------------
    _S("ba_basic", 10, "把 + object + verb + something", "把门关上 / 把药吃了 / 把桌子擦一擦",
       "Say what you do to a specific thing.",
       notes=_BA,
       markers=("把",), level=3, core=True),
    _S("ba_result", 10, "把 + object + verb + result", "把饭吃完 / 把门关好 / 把钱用光",
       "Say what result you bring about on a specific thing.",
       notes=_BA + "Covers 把 + O + V + 好/完/光/掉/清楚.",
       markers=("把",), level=3, core=True),
    _S("ba_direction", 10, "把 + object + verb + direction", "把书拿出来 / 把垃圾拿出去",
       "Say where you move a specific thing.",
       notes=_BA + "把车开进去 / 把东西拿回来 / 把手机拿出来.",
       markers=("把",), level=3),
    _S("ba_location", 10, "把 + object + verb + 在 / 到 + place", "把车停在外面 / 把书放在桌上",
       "Say where you put or send a specific thing.",
       notes=_BA + "Here 把 is required: 把车停在楼下 / 把孩子送到学校 / 把钱放在"
             "钱包里.",
       markers=("把",), level=3, core=True),
    _S("ba_quantity", 10, "把 + object + verb + how much", "把这本书看了两遍 / 把房间打扫一下",
       "Say how much you did to a specific thing.",
       notes=_BA + "把衣服洗一洗 / 把门推开一点.",
       markers=("把",), level=4),
    _S("ba_le", 10, "把 + object + verb + 了 — dealt with, gone", "把药吃了 / 把旧衣服丢了",
       "Say you've dealt with or got rid of something.",
       notes=_BA + "Common with 丢, 卖, 吃, 喝, 关, 忘: 你把冷气关了吗？",
       markers=("把",), level=3),
    _S("ba_required", 10, "When 把 is needed", "把钱还给他 / 把美金换成令吉",
       "Recognise sentences that need 把.",
       notes=_BA + "When the object is moved or changed and the verb is followed by "
             "在 / 到 / 给 / 成 + something: 把书还给图书馆, 把字写成……, 把车停在…….",
       markers=("把",), level=4),
    _S("ba_cannot", 10, "When 把 doesn't work", "我喜欢这本书 (不是：把这本书喜欢)",
       "Recognise sentences where 把 can't be used.",
       notes=_BA + "No 把 with verbs that don't change the object: 喜欢, 知道, 看见, 觉得, "
             "有, 是, 在; nor with unspecified new objects. Identify tasks: which "
             "sentence could take 把? Only correct sentences may be spoken or shown "
             "as models.",
       level=4),
    _S("ba_vs_active", 10, "把 vs an ordinary sentence", "我吃完了饭 ↔ 我把饭吃完了",
       "Choose between focusing on what happens to a known thing and a plain statement.",
       notes=_BA + "把 fits a known object being dealt with (把那碗饭吃完); a plain "
             "sentence for general or new objects (我想吃饭).",
       contrast=("ba_basic",), level=3, core=True, kind="contrast", also_in=(30,)),

    # ------------------------------------------------------------------
    # 11. Passive
    # ------------------------------------------------------------------
    _S("bei_basic", 11, "被 + doer + verb + something", "我的车被他撞坏了。",
       "Say what happened to someone or something — usually unwelcome.",
       notes=_BEI,
       markers=("被",), level=3, core=True),
    _S("bei_result", 11, "被 + verb + result", "被偷走了 / 被吃光了 / 被撞坏了",
       "Say what result something suffered.",
       notes=_BEI,
       markers=("被",), level=3),
    _S("bei_direction", 11, "被 + verb + direction", "被赶出去了 / 被风吹下来了",
       "Say where something or someone was moved to.",
       notes=_BEI,
       markers=("被",), level=4),
    _S("bei_le", 11, "被 + … + verb + 了", "被骂了 / 被偷了 / 被抓了",
       "Report that something happened to someone.",
       notes=_BEI + "Short everyday reports: 他今天被老板骂了.",
       markers=("被",), level=3),
    _S("bei_no_agent", 11, "被 without the doer", "我的钱包被偷了。",
       "Report what happened when the doer is unknown or unimportant.",
       notes=_BEI,
       markers=("被",), level=3),
    _S("bei_rang_jiao", 11, "让 / 叫 / 给 — spoken passives", "衣服让雨淋湿了 / 我的手机给他弄坏了",
       "Recognise the everyday spoken ways of saying 被.",
       notes=_BEI + "让 and 叫 need the doer; 给 can drop it (手机给偷了). 给 is very "
             "common in Malaysian speech.",
       markers=("让", "叫", "给", "被"), level=4),
    _S("bei_unfortunate", 11, "被 for bad news, plain sentences for neutral results",
       "我被骂了 ↔ 饭做好了",
       "Know when 被 fits and when a plain sentence reports a result better.",
       notes=_BEI + "Neutral results usually need no marker: 饭做好了, 信寄出去了, 票"
             "卖完了. Using 被 there sounds odd or complaining.",
       level=4),
    _S("bei_vs_active", 11, "被 vs an ordinary sentence", "他打了我 ↔ 我被他打了",
       "Choose whether to focus on the doer or on the one affected.",
       notes=_BEI,
       contrast=("bei_basic",), level=3, kind="contrast", also_in=(30,)),
    _S("ba_vs_bei", 11, "把 vs 被", "他把我的车撞坏了 ↔ 我的车被他撞坏了",
       "Tell 'the doer did this to it' from 'it had this done to it'.",
       notes=_BA + _BEI + "Same event, different starting point.",
       contrast=("ba_basic", "bei_basic"), markers=("把", "被"), level=4, core=True,
       kind="contrast", also_in=(30,)),

    # ------------------------------------------------------------------
    # 12. 是……的
    # ------------------------------------------------------------------
    _S("shi_de", 12, "是……的 — when, where, how, who", "我是昨天到的。",
       "Focus on a detail of something that has already happened.",
       notes="The event is already known; 是……的 highlights when / where / how / who. "
             "是 before the detail, 的 at the end (or before an object: 我是昨天买的票). "
             "是 is often dropped in speech. Never for future events.",
       markers=("的",), level=3, core=True),
    _S("shi_de_time", 12, "是 + time + ……的", "我是上个礼拜到的。",
       "Say when something happened.",
       notes="Focus on time: 你是几点放工的？",
       markers=("的",), level=3),
    _S("shi_de_place", 12, "是在 + place + ……的", "这个是在巴刹买的。",
       "Say where something happened.",
       notes="Focus on place: 你们是在哪里认识的？",
       markers=("的",), level=3),
    _S("shi_de_manner", 12, "是 + how + ……的", "我是搭巴士来的。",
       "Say how something was done.",
       notes="Focus on manner or means: 是驾车去的 / 是走路来的.",
       markers=("的",), level=3),
    _S("shi_de_agent", 12, "是 + who + ……的", "这个菜是我妈做的。",
       "Say who did it.",
       notes="Focus on the doer: 是我朋友给我的 / 是谁告诉你的？",
       markers=("的",), level=3),
    _S("shi_de_question", 12, "Asking with 是……的", "你是什么时候到的？/ 是不是你拿的？",
       "Ask about when, where, how or who.",
       notes="Question word inside: 你是怎么来的？/ 是在哪里买的？",
       markers=("的",), level=3),
    _S("shi_de_neg", 12, "不是……的", "我不是坐飞机来的，是搭巴士来的。",
       "Correct a wrong assumption about how, when or where.",
       notes="不是 + detail + 的, often followed by the right detail.",
       markers=("不是",), level=3),
    _S("shi_de_vs_le", 12, "是……的 vs 了", "他来了 ↔ 他是昨天来的",
       "Tell reporting that something happened from focusing on a detail of it.",
       notes="了 reports the event as news; 是……的 assumes it and asks or tells "
             "when/where/how/who. Never describe 了 as past tense.",
       contrast=("shi_de", "le_verb"), level=3, core=True, kind="contrast",
       also_in=(30,)),

    # ------------------------------------------------------------------
    # 13. Comparison
    # ------------------------------------------------------------------
    _S("bi_adj", 13, "A 比 B + adjective", "他比我高。",
       "Say one thing is more … than another.",
       notes="No 很 / 非常 after 比 (NOT 比我很高); use 更, 还, or an amount.",
       markers=("比",), level=2, core=True),
    _S("bi_verb", 13, "A 比 B + verb", "他比我会做菜。/ 我比他喜欢吃辣。",
       "Compare how much or how well people do something.",
       notes="比 + person + modal/verb phrase: 他比我早到, 他比我能吃.",
       markers=("比",), level=3),
    _S("bi_quantity", 13, "A 比 B + adjective + amount", "他比我大三岁。/ 这个比那个贵十块。",
       "Say by how much one thing is more than another.",
       notes="Amount after the adjective: 贵一点 / 贵多了 / 高得多 / 大三岁.",
       markers=("比",), level=3),
    _S("bi_duo_shao", 13, "比……多 / 少 + verb + amount", "他比我多吃了一碗。",
       "Say someone did more or less of something than another.",
       notes="多/少 before the verb, amount after: 他比我少做了两个钟头.",
       markers=("比",), level=4),
    _S("bi_zao_wan", 13, "比……早 / 晚 + verb", "他比我早到十分钟。",
       "Say someone did something earlier or later than another.",
       notes="早/晚 before the verb, amount after: 我比他晚放工.",
       markers=("比",), level=3),
    _S("bi_geng", 13, "比……更…… — even more", "今天比昨天更热。",
       "Say one thing is even more so than another.",
       notes="更 after the comparison, before the adjective.",
       markers=("更",), level=2),
    _S("bi_hai", 13, "比……还(要)…… — even more (surprise)", "他比我还高。",
       "Say something is even more so — surprisingly.",
       notes="Implies the other is already quite so: 他比我还高 (and I'm tall). Covers "
             "还要: 今天比昨天还要热.",
       markers=("还",), level=3),
    _S("meiyou_name", 13, "A 没有 B (那么) + adjective — not as … as", "我没有他那么高。",
       "Say one thing isn't as … as another.",
       notes="The usual negative of 比 (不比 means 'no more than'). 那么/这么 optional: "
             "今天没有昨天热.",
       markers=("没有",), level=3, core=True),
    _S("buru", 13, "A 不如 B — not as good as", "这家不如那家好吃。",
       "Say one thing isn't as good as another.",
       notes="不如 + B (+ adjective): 我的华语不如你 / 坐巴士不如驾车快.",
       markers=("不如",), level=4),
    _S("gen_yiyang", 13, "A 跟 / 和 B 一样 — the same as", "我跟你一样高。",
       "Say two things are the same (in some way).",
       notes="跟/和 B 一样 (+ adjective): 他的手机跟我的一样 / 这里跟怡保一样热.",
       markers=("一样",), level=2, core=True),
    _S("gen_bu_yiyang", 13, "A 跟 B 不一样 — different from", "马来西亚的华语跟中国的不一样。",
       "Say two things are different.",
       notes="不 before 一样: 跟……不一样. Also 有什么不一样？",
       markers=("不一样",), level=2),
    _S("xiang_yiyang", 13, "像……一样 — like", "他跑得像风一样快。",
       "Say something is like something else.",
       notes="Likening, often figurative: 像家人一样, 像小孩一样. Contrast 跟……一样 "
             "(literally the same).",
       markers=("像",), level=3, core=True),
    _S("xiang_name", 13, "像……那么 / 这么 — as … as", "他像他哥哥那么高。",
       "Say something is as … as something else.",
       notes="Often negative or in questions: 没有像今天这么热过 / 有像他那么高吗？",
       markers=("那么", "这么"), level=3),
    _S("xiang_shide", 13, "像……似的 — as if", "他像小孩似的。",
       "Say something is as if it were something else.",
       notes="Spoken, vivid: 跑得像飞似的 / 好像不认识我似的.",
       markers=("似的",), level=4),
    _S("bi_vs_meiyou", 13, "比 vs 没有……那么", "他比我高 ↔ 我没有他那么高",
       "Say the same comparison from either side.",
       notes="Positive with 比, negative with 没有……那么. 不比 is not the plain "
             "negative (不比他高 = no taller than him).",
       contrast=("bi_adj", "meiyou_name"), markers=("比", "没有"), level=3, core=True,
       kind="contrast", also_in=(30,)),
    _S("gen_vs_xiang", 13, "跟……一样 vs 像……一样", "他跟我一样高 ↔ 他像大人一样",
       "Tell 'the same as' from 'like'.",
       notes="跟……一样 compares equals; 像……一样 likens (often figurative).",
       contrast=("gen_yiyang", "xiang_yiyang"), markers=("一样",), level=3,
       kind="contrast", also_in=(30,)),
    _S("yue_yue", 13, "越……越…… — the more … the more …", "天越热，人越少。/ 越快越好。",
       "Link two things that increase together.",
       notes="越 + A, 越 + B; subjects can differ. 越快越好 = the sooner the better.",
       contrast=("yuelaiyue",), markers=("越",), level=3, core=True, also_in=(31, 32, 34)),
    _S("yuelaiyue", 13, "越来越 + adjective — more and more", "越来越热 / 越来越喜欢",
       "Say something keeps getting more so.",
       notes="越来越 + adjective or psychological verb; usually with 了: 我的华语越来"
             "越好了.",
       contrast=("yue_yue",), markers=("越来越",), level=2, core=True, also_in=(31, 32, 34)),
    _S("yue_v_yue", 13, "越 + verb + 越…… — the more you do it", "越吃越想吃 / 越想越生气",
       "Say doing something more makes something increase.",
       notes="Same verb or subject: 越说越快, 越看越喜欢.",
       markers=("越",), level=3),
    _S("geng", 13, "更 + adjective — even more", "我更喜欢这个。",
       "Say something is even more so (compared with before or another).",
       notes="Without 比 too: 今天更热 / 我更喜欢巴刹.",
       markers=("更",), level=2, also_in=(14,)),
    _S("jile", 13, "Adjective + 极了 — extremely", "好吃极了 / 累极了",
       "Say something is extremely so.",
       notes="After the adjective, spoken and emphatic.",
       markers=("极了",), level=3),
    _S("tai_le", 13, "太……了 — too / so", "太贵了 / 太好了!",
       "Say something is too much — or, excitedly, really great.",
       notes="Complaint (太贵了, 太辣了) or delight (太好了!). 不太 + adjective = not "
             "very (不太贵).",
       markers=("太",), level=1, also_in=(14,)),
    _S("zhen_a", 13, "真……啊 — how …!", "真好吃啊! / 真热啊!",
       "Exclaim how something is.",
       notes="真 + adjective as a comment; it can't sit inside a noun phrase (很好的人, "
             "NOT 真好的人).",
       markers=("真",), level=2),
    _S("hao_a", 13, "好……啊 — so …!", "好热啊! / 好累啊!",
       "Exclaim that something is so … (very common in Malaysia).",
       notes="好 = very in exclamations: 好贵啊, 好香啊, 好久不见.",
       markers=("好",), level=2),
    _S("duo_a", 13, "多……啊 — how …!", "多漂亮啊! / 多好啊!",
       "Exclaim how … something is.",
       notes="Emphatic, slightly more expressive than 真/好: 那里的风景多美啊!",
       markers=("多",), level=3),

    # ------------------------------------------------------------------
    # 14. Adverbials
    # ------------------------------------------------------------------
    _S("feichang", 14, "非常 + adjective — extremely", "非常好 / 非常喜欢",
       "Say something is extremely so.",
       notes="Stronger than 很; also with psychological verbs (非常喜欢, 非常担心).",
       markers=("非常",), level=1),
    _S("zhen_adj", 14, "真 + adjective — really", "你真好 / 这里真热",
       "Say something really is so — an exclamatory comment.",
       notes="Comment only; not inside a noun phrase (NOT 真好的人).",
       markers=("真",), level=1),
    _S("tebie", 14, "特别 + adjective — especially", "今天特别热 / 我特别喜欢",
       "Say something is especially so.",
       notes="特别 + adjective/verb; also 'especially' before a noun (特别是周末).",
       markers=("特别",), level=2),
    _S("ting_adj", 14, "蛮 / 挺 + adjective — quite, pretty", "蛮好的 / 挺好的",
       "Say something is quite or pretty so.",
       notes="Malaysians say 蛮 (蛮好吃的, 蛮贵的); 挺 is mainland. Produce with 蛮, "
             "recognise 挺. Often with a final 的.",
       markers=("蛮", "挺"), level=2),
    _S("youdian", 14, "有点 + adjective — a bit (too)", "有点贵 / 有点累",
       "Say something is a bit too much — usually unwelcome.",
       notes="Before an adjective or feeling: 有点冷, 有点担心. Mostly for "
             "undesirable things (NOT 有点好). Contrast 一点 after an adjective (便宜"
             "一点).",
       contrast=("yidian",), markers=("有点", "有一点"), level=2),
    _S("de_manner", 14, "Adjective + 地 + verb — how it's done", "认真地做 / 高兴地说 / 慢慢地走",
       "Describe the manner of an action before the verb.",
       notes="地 links a description to the verb; often dropped with doubled "
             "adjectives (慢慢走). Contrast with 得 after the verb.",
       contrast=("deg_de",), markers=("地",), level=3),
    _S("haohao", 14, "好好 + verb — properly, well", "好好休息 / 好好学 / 好好想想",
       "Tell someone to do something properly.",
       notes="Advice and encouragement: 你好好休息吧.",
       markers=("好好",), level=2),
]

LISTED = {
    9: [
        ("V + 完 — finish", "res_wan"),
        ("V + 好 — successfully complete", "res_hao"),
        ("V + 到 — reach/find", "res_dao"),
        ("V + 见 — perceive", "res_jian"),
        ("V + 懂 — understand", "res_dong"),
        ("V + 清楚 — make clear", "res_qingchu"),
        ("V + 错 — do incorrectly", "res_cuo"),
        ("V + 对 — do correctly", "res_dui"),
        ("V + 开 — open/separate", "res_kai"),
        ("V + 光 — completely use/eat", "res_guang"),
        ("V + 住 — successfully hold/retain", "res_zhu"),
        ("V + 成 — become/turn into", "res_cheng"),
        ("V + 走 — carry away", "res_zou"),
        ("V + 掉 — remove/disappear", "res_diao"),
        ("Resultative complement negation", "res_negation"),
        ("Resultative complement + 了", "res_le"),
        ("Resultative complement + 过", "res_guo"),
        ("V + 得 + complement", "pot_de"),
        ("V + 不 + complement", "pot_bu"),
        ("吃得完 / 吃不完", "pot_chi_wan"),
        ("听得懂 / 听不懂", "pot_ting_dong"),
        ("看得见 / 看不见", "pot_kan_jian"),
        ("做得到 / 做不到", "pot_zuo_dao"),
        ("Potential complement questions", "pot_question"),
        ("Potential vs 能 / 可以", "pot_vs_neng"),
        ("V + 得 + adjective", "deg_de"),
        ("V + 得 + 很 + adjective", "deg_de_hen"),
        ("V + 得 + adjective + complement", "deg_de_clause"),
        ("Adjective + 得不得了", "deg_budeliao"),
        ("……得很", "deg_dehen"),
        ("Degree complement vs adverbial adjective", "deg_vs_adverbial"),
        ("V + 来 / 去", "dir_lai_qu"),
        ("V + 上 / 下 / 进 / 出 / 回 / 过", "dir_simple"),
        ("V + directional complement + 来 / 去", "dir_compound"),
        ("上来 / 上去", "dir_shang"),
        ("下来 / 下去", "dir_xia"),
        ("进来 / 进去", "dir_jin"),
        ("出来 / 出去", "dir_chu"),
        ("回来 / 回去", "dir_hui"),
        ("过来 / 过去", "dir_guo"),
        ("拿来 / 拿去", "dir_na"),
        ("Directional complement with objects", "dir_object"),
        ("Literal vs extended directional meaning", "dir_extended"),
    ],
    10: [
        ("把 + object + verb", "ba_basic"),
        ("把 + object + result complement", "ba_result"),
        ("把 + object + directional complement", "ba_direction"),
        ("把 + object + location", "ba_location"),
        ("把 + object + quantity", "ba_quantity"),
        ("把 + object + V + 了", "ba_le"),
        ("把 + object + V + 好/完/光/etc.", "ba_result"),
        ("When 把 is required/natural", "ba_required"),
        ("When 把 cannot normally be used", "ba_cannot"),
        ("Active vs 把 construction", "ba_vs_active"),
    ],
    11: [
        ("被 + agent + verb", "bei_basic"),
        ("被 + resultative complement", "bei_result"),
        ("被 + directional complement", "bei_direction"),
        ("被 + 了", "bei_le"),
        ("Agent omitted after 被", "bei_no_agent"),
        ("让 / 叫 / 给 as passive markers", "bei_rang_jiao"),
        ("被 vs active sentence", "bei_vs_active"),
        ("被 vs 把", "ba_vs_bei"),
        ("Unfortunate-event passive vs neutral passive", "bei_unfortunate"),
    ],
    12: [
        ("是……的 — focus on completed-event circumstances", "shi_de"),
        ("Time focus: 是……买的", "shi_de_time"),
        ("Place focus: 是在……买的", "shi_de_place"),
        ("Manner focus: 是……去的", "shi_de_manner"),
        ("Agent focus: 是……给我的", "shi_de_agent"),
        ("是不是……的", "shi_de_question"),
        ("Negating 是……的", "shi_de_neg"),
        ("是……的 vs 了", "shi_de_vs_le"),
        ("是……的 vs ordinary past statement", "shi_de_vs_le"),
    ],
    13: [
        ("A 比 B + adjective", "bi_adj"),
        ("A 比 B + verb", "bi_verb"),
        ("A 比 B + quantity", "bi_quantity"),
        ("比……多/少……", "bi_duo_shao"),
        ("比……早/晚……", "bi_zao_wan"),
        ("比……更……", "bi_geng"),
        ("比……还……", "bi_hai"),
        ("没有 A 那么…… — not as…as", "meiyou_name"),
        ("不如…… — not as good as", "buru"),
        ("跟 / 和……一样……", "gen_yiyang"),
        ("跟 / 和……不一样", "gen_bu_yiyang"),
        ("像……一样……", "xiang_yiyang"),
        ("像……那么…… / 像……这么……", "xiang_name"),
        ("像……似的", "xiang_shide"),
        ("比 vs 没有……那么……", "bi_vs_meiyou"),
        ("跟……一样 vs 像……一样", "gen_vs_xiang"),
        ("越……越……", "yue_yue"),
        ("越来越……", "yuelaiyue"),
        ("越来越 + adjective", "yuelaiyue"),
        ("越 V 越……", "yue_v_yue"),
        ("最……", "zui_adj"),
        ("更……", "geng"),
        ("还要……", "bi_hai"),
        ("极了", "jile"),
        ("得不得了", "deg_budeliao"),
        ("太……了", "tai_le"),
        ("真……啊", "zhen_a"),
        ("好……啊", "hao_a"),
        ("多……啊", "duo_a"),
    ],
    14: [
        ("很 + adjective", "hen_adj"),
        ("非常 + adjective", "feichang"),
        ("真 + adjective", "zhen_adj"),
        ("太 + adjective", "tai_le"),
        ("更 + adjective", "geng"),
        ("最 + adjective", "zui_adj"),
        ("比较 + adjective", "bijiao_adj"),
        ("特别 + adjective", "tebie"),
        ("挺 + adjective", "ting_adj"),
        ("有点 / 有一点 + adjective", "youdian"),
        ("一点也不……", "yidian_bu"),
        ("一点都不……", "yidian_bu"),
        ("地 — manner adverbial", "de_manner"),
        ("Adjective + 地 + verb", "de_manner"),
        ("慢慢地、认真地、仔细地 etc.", "de_manner"),
        ("好好 + verb", "haohao"),
        ("Verb + 得 + degree", "deg_de"),
        ("的 vs 地 vs 得", "de_de_de"),
    ],
}
