# src/grammar_data_6.py
"""Grammar curriculum, groups 30-36: the high-value contrast pairs (each a
dedicated contrast drill), advanced everyday structures, advanced
comparison/condition/correlatives, spoken fluency, and the core automation
set."""

from grammar_schema import Structure

SECTIONS = {
    30: "High-Value Contrast Pairs",
    31: "Advanced but Useful Everyday Structures",
    32: "Advanced Comparison / Similarity",
    33: "Advanced Condition & Concession",
    34: "Advanced Correlative Structures",
    35: "Structures for Natural Spoken Fluency",
    36: "Core Grammar Automation Set",
}

_S = Structure
_PAIR = ("Contrast drill: the learner must hear or choose which form fits the "
         "meaning, from minimal pairs and real situations - not recite rules. ")
_SPOKEN = ("Drill as reactions in real exchanges: hear a line, respond naturally. ")

STRUCTURES = [
    # ------------------------------------------------------------------
    # 30. High-value contrast pairs (those not already drilled elsewhere)
    # ------------------------------------------------------------------
    _S("lai_vs_qu", 30, "来 vs 去", "你来我家 ↔ 我去你家 · 拿来 ↔ 拿去",
       "Choose come or go — as a verb and after a verb — from where the speaker is.",
       notes=_PAIR + "Towards the speaker = 来; away = 去. Phone calls and "
             "invitations are the best test (你几点来？ / 我明天去你那里).",
       contrast=("lai_qu", "dir_lai_qu"), markers=("来", "去"), level=2, core=True,
       kind="contrast"),
    _S("xiang_vs_yao", 30, "想 vs 要", "我想去 ↔ 我要去",
       "Hear how firm an intention is: would like vs will / must.",
       notes=_PAIR + "想 = would like / thinking of (soft); 要 = will, intend firmly, "
             "need to. 不想 = don't want to; 不要 = don't!",
       contrast=("xiang_want", "yao_want"), markers=("想", "要"), level=2, core=True,
       kind="contrast"),
    _S("yao_vs_kuaiyao", 30, "要 vs 快要", "我要走 ↔ 我快要走了",
       "Tell 'intend to' from 'about to'.",
       notes=_PAIR + "要 alone = want / going to; 快要……了 = any moment now. The "
             "final 了 plus 快 is what signals imminence.",
       contrast=("yao_want", "kuaiyao_le"), markers=("要",), level=3, kind="contrast"),
    _S("dao_vs_zai", 30, "到 vs 在", "我到巴刹了 ↔ 我在巴刹 · 走到门口 ↔ 站在门口",
       "Tell arriving or reaching from being somewhere.",
       notes=_PAIR + "到 = arrive / reach an end point; 在 = be located. After verbs: "
             "V到 = get as far as; V在 = stay at.",
       contrast=("dao_place", "zai_place"), markers=("到", "在"), level=2,
       kind="contrast"),
    _S("you_vs_shi", 30, "有 vs 是", "我有一个问题 ↔ 我是老师 · 桌上有书 ↔ 桌上是书",
       "Tell 'have / there is' from 'is'.",
       notes=_PAIR + "有 = possession or existence (new information); 是 = identity "
             "or what occupies a place.",
       contrast=("you_exist", "shi_identity"), markers=("有", "是"), level=2,
       kind="contrast"),
    _S("yiyang_vs_xiangsi", 30, "一样 vs 相似", "我跟你一样 ↔ 这两个很像",
       "Tell 'the same' from 'similar'.",
       notes=_PAIR + "一样 = identical in that respect; 相似 = similar (formal and "
             "written). In everyday Malaysian speech 'similar' is 很像 or 差不多 - "
             "recognise 相似, produce 很像 / 差不多.",
       contrast=("gen_yiyang",), markers=("一样", "相似", "像", "差不多"), level=3,
       kind="contrast"),
    _S("yue_vs_yuelaiyue", 30, "越来越 vs 越……越……", "越来越热 ↔ 越走越热",
       "Tell 'more and more over time' from 'the more A, the more B'.",
       notes=_PAIR + "越来越 = one thing changing over time; 越 A 越 B = B rises with A.",
       contrast=("yuelaiyue", "yue_yue"), markers=("越",), level=3, kind="contrast"),
    _S("hai_vs_zai", 30, "还 vs 再", "他还在 ↔ 他明天再来",
       "Tell 'still / also' from 'again (next time) / then'.",
       notes=_PAIR + "还 = still, also (还没, 还要). Future repetition: 再来 is the "
             "default; 还来 suggests carrying on as before. Only 再 means 'then / not "
             "until' (吃了再走).",
       contrast=("hai_still", "zai_again"), markers=("还", "再"), level=3,
       kind="contrast"),
    _S("zhi_vs_cai", 30, "只 vs 才", "我只有十块 ↔ 我才有十块",
       "Tell a plain 'only' from 'only (not much!)'.",
       notes=_PAIR + "只 limits (only this); 才 + amount adds 'fewer than expected' "
             "(才十块!). 才 also means 'not until'.",
       contrast=("zhi_only", "cai_only"), markers=("只", "才"), level=3,
       kind="contrast"),
    _S("ye_vs_dou", 30, "也 vs 都", "我也去 ↔ 我们都去",
       "Tell 'also' from 'all / both'.",
       notes=_PAIR + "也 adds to something already mentioned; 都 covers the whole "
             "group before it. Together: 我们也都去.",
       contrast=("ye_also", "dou_meanings"), markers=("也", "都"), level=2,
       kind="contrast"),
    _S("dou_vs_quan", 30, "都 vs 全", "他们都来了 ↔ 全家都来了",
       "Tell the adverb 都 from 全 (the whole of).",
       notes=_PAIR + "都 is an adverb before the verb; 全 describes a whole noun (全家, "
             "全身, 全世界) or means 'completely' (全错了). 全都 = every one of them.",
       contrast=("dou_meanings",), markers=("都", "全"), level=3, kind="contrast"),
    _S("yidian_vs_youdian", 30, "一点 vs 有点", "便宜一点 ↔ 有点贵",
       "Tell 'a bit more …' from 'a bit too …'.",
       notes=_PAIR + "一点 after an adjective (requests, comparisons) or before a "
             "noun; 有点 before an adjective, usually a complaint.",
       contrast=("yidian", "youdian"), markers=("一点", "有点"), level=2,
       kind="contrast"),
    _S("ji_vs_duoshao", 30, "几 vs 多少", "几个人？ ↔ 多少人？",
       "Choose between asking for a small number and any number.",
       notes=_PAIR + "几 expects a small number and needs a measure word; 多少 is "
             "open-ended, measure word optional, and used for prices.",
       contrast=("ji_howmany", "duoshao"), markers=("几", "多少"), level=2,
       kind="contrast"),
    _S("gang_vs_gangcai", 30, "刚 vs 刚才", "我刚到 ↔ 刚才我没听到",
       "Tell 'just (did)' from 'just now' as a time.",
       notes=_PAIR + "刚/刚刚 is an adverb before the verb (and can mean 'only just': "
             "刚来一个礼拜); 刚才 is a time word that can start a sentence and be "
             "negated.",
       contrast=("gang", "gangcai"), markers=("刚",), level=3, kind="contrast"),
    _S("yijing_vs_guo", 30, "已经 vs 过", "我已经吃了 ↔ 我吃过",
       "Tell 'already done (now)' from 'have done it before'.",
       notes=_PAIR + "已经……了 = done by now; V过 = experience at some time. Both: 我"
             "已经去过了.",
       contrast=("yijing_le", "guo_exp"), markers=("已经", "过"), level=3,
       kind="contrast"),
    _S("xian_vs_zai", 30, "先 vs 再", "先吃饭 ↔ 吃了饭再去",
       "Put steps in order: first, then.",
       notes=_PAIR + "先 marks the first step; 再 the later one (then / not until).",
       contrast=("xian", "zai_again"), markers=("先", "再"), level=2, kind="contrast"),
    _S("zai_vs_ranhou", 30, "再 vs 然后", "吃了饭再去 ↔ 我们吃了饭，然后去巴刹",
       "Tell 'then (plans, not until)' from 'and then (telling a sequence)'.",
       notes=_PAIR + "再 is for plans and instructions (future only); 然后 narrates "
             "past or future sequences.",
       contrast=("xian_zai", "ranhou"), markers=("再", "然后"), level=3,
       kind="contrast"),
    _S("yinwei_vs_jiran", 30, "因为……所以 vs 既然……就", "因为下雨，所以我不去 ↔ 既然下雨，就别去了",
       "Tell giving a reason from drawing a conclusion from a known fact.",
       notes=_PAIR + "因为 explains; 既然 takes an agreed fact and suggests or "
             "concludes (often with 就 / 吧).",
       contrast=("yinwei_suoyi", "jiran_jiu"), markers=("因为", "既然"), level=3,
       kind="contrast"),
    _S("suiran_vs_jishi", 30, "虽然……但是 vs 即使……也", "虽然下雨，我还是去了 ↔ 即使下雨，我也去",
       "Tell 'although (a fact)' from 'even if (a hypothesis)'.",
       notes=_PAIR + "虽然 concedes something true; 即使 imagines something that may "
             "not happen.",
       contrast=("suiran_danshi", "jishi_ye"), markers=("虽然", "即使"), level=3,
       kind="contrast"),
    _S("ruguo_vs_zhiyao", 30, "如果……就 vs 只要……就", "如果有时间，我就去 ↔ 只要有时间，我就去",
       "Tell a plain 'if' from 'as long as'.",
       notes=_PAIR + "如果 = if; 只要 = that's all it takes.",
       contrast=("ruguo_jiu", "zhiyao_jiu"), markers=("如果", "只要"), level=3,
       kind="contrast"),
    _S("yijiu_vs_caijiu", 30, "一……就 vs 才……就", "我一到家就睡觉 ↔ 他才到就走了",
       "Tell 'as soon as' from 'had only just … when'.",
       notes=_PAIR + "一……就 = as soon as / whenever; 才(刚)……就 = had only just … "
             "when (surprisingly soon).",
       contrast=("yi_jiu", "jiu_early"), markers=("一", "才", "刚"), level=4,
       kind="contrast"),
    _S("keyi_vs_dei", 30, "可以 / 能 vs 得 / 不得", "你可以走了 ↔ 你得走了 · 不得吸烟",
       "Tell 'may, can' from 'must' and 'must not'.",
       notes=_PAIR + "可以/能 = may, can; 得 (děi) = have to; 不得 = must not (formal "
             "notices); 不用 = don't have to.",
       contrast=("keyi", "dei_must"), markers=("可以", "能", "得", "不得", "不用"),
       level=4, kind="contrast"),
    _S("res_vs_pot", 30, "Result vs can / can't manage", "没听懂 ↔ 听不懂 · 吃完了 ↔ 吃得完",
       "Tell 'did(n't) get the result' from 'can(’t) get the result'.",
       notes=_PAIR + "没听懂 = didn't understand (that time); 听不懂 = can't understand. "
             "吃完了 = finished; 吃得完 = can finish.",
       contrast=("res_negation", "pot_bu"), level=3, core=True, kind="contrast"),

    # ------------------------------------------------------------------
    # 31. Advanced but useful everyday structures
    # ------------------------------------------------------------------
    _S("suizhe", 31, "随着 — as, along with (a change)", "随着天气变热，喝冰水的人越来越多。",
       "Link a change to another that follows it.",
       notes="Usually at the start; often with 越来越.",
       markers=("随着",), level=4),
    _S("suibian", 31, "随便 — as you like, casually", "随便坐 / 随便你 / 随便吃一点",
       "Say anything goes, or do something casually.",
       notes=_SPOKEN + "Invitations (随便坐), indifference (随便你, 随便啦).",
       markers=("随便",), level=2),
    _S("zhihao", 31, "只好 / 只得 — have no choice but", "巴士没来，我只好走路。",
       "Say you had to settle for something.",
       notes="只得 is the written form.",
       contrast=("zhineng",), markers=("只好", "只得"), level=3),
    _S("zhineng", 31, "只能 — can only", "我只能等。/ 今天只能这样了。",
       "Say it's the only thing possible.",
       notes="Ability or possibility limited to one option.",
       contrast=("zhihao",), markers=("只能",), level=2),
    _S("zhongyu", 31, "终于 — finally (after waiting)", "终于到了!/ 他终于来了。",
       "Say something happened at last.",
       notes="Relief or satisfaction after a wait; usually with 了.",
       contrast=("zongsuan",), markers=("终于",), level=2),
    _S("zongsuan", 31, "总算 — at last (with relief)", "总算做完了!/ 总算不下雨了。",
       "Say something finally worked out.",
       notes="Spoken; stresses relief more than 终于.",
       contrast=("zhongyu",), markers=("总算",), level=3),
    _S("jingran", 31, "竟然 / 居然 — unexpectedly, would you believe", "他竟然没来!/ 居然这么便宜!",
       "Express surprise that something happened.",
       notes="居然 is more spoken; both before the verb.",
       markers=("竟然", "居然"), level=4),
    _S("faner", 31, "反而 — instead, on the contrary", "吃了药，反而更不舒服。",
       "Say the result was the opposite of what you'd expect.",
       notes="他不但没生气，反而笑了.",
       markers=("反而",), level=4),
    _S("youqi", 31, "尤其(是) / 特别是 — especially", "我喜欢水果，尤其是榴莲。",
       "Single out the strongest example.",
       notes="特别是 is the everyday equivalent.",
       markers=("尤其", "特别是"), level=3),
    _S("zhishao_zuiduo", 31, "至少 / 至多 — at least / at most", "至少三个钟头 / 最多五十块",
       "Set a minimum or maximum.",
       notes="Spoken Malaysian often 最少 / 最多; 至多 is formal.",
       markers=("至少", "至多", "最少", "最多"), level=2),
    _S("chadian", 31, "差点 / 差一点 — almost (but not)", "我差点迟到。/ 差一点就摔倒了。",
       "Say something nearly happened.",
       notes="Never 差点儿. For unwanted events 差点没…… usually means the same as "
             "差点 (almost); keep examples to plain 差点.",
       contrast=("jihu",), markers=("差点", "差一点"), level=3),
    _S("jihu", 31, "几乎 — almost, nearly", "几乎每天都去。/ 几乎没有人。",
       "Say something is nearly total.",
       notes="几乎 describes extent (nearly all / nearly none); 差点 describes an "
             "event that almost happened.",
       contrast=("chadian",), markers=("几乎",), level=3),
    _S("jieguo", 31, "结果 — in the end, as it turned out", "我等了一个钟头，结果他没来。",
       "Say how things turned out.",
       notes=_SPOKEN + "Also 结果呢？ = and then what happened?",
       markers=("结果",), level=3),
    _S("kan_ting_qilai", 31, "看起来 / 听起来 — it looks / it sounds", "看起来要下雨。/ 听起来不错。",
       "Give an impression from how something looks or sounds.",
       notes="他看起来很累 / 这个主意听起来很好.",
       contrast=("haoxiang",), markers=("看起来", "听起来"), level=2),
    _S("kanlai", 31, "看来 — it seems (judging from this)", "看来他不来了。",
       "Draw a conclusion from what you see.",
       notes="At the start of the sentence; a conclusion, not just an appearance.",
       markers=("看来",), level=3),
    _S("haoxiang", 31, "好像 / 似乎 — seems, as if", "好像要下雨。/ 他好像不高兴。",
       "Say something seems to be so.",
       notes="似乎 is the formal equivalent.",
       markers=("好像", "似乎"), level=2),
    _S("tingshuo", 31, "听说 — I hear (that)", "听说你要搬到怡保？",
       "Pass on something you've heard.",
       notes="我听说那家很好吃.",
       contrast=("jushuo",), markers=("听说",), level=2),
    _S("jushuo", 31, "据说 / 据 — reportedly, according to", "据说明天会很热。",
       "Report information from others more formally.",
       notes="据 + source (据报道) is written.",
       contrast=("tingshuo",), markers=("据说", "据"), level=3),

    # ------------------------------------------------------------------
    # 32. Advanced comparison
    # ------------------------------------------------------------------
    _S("gen_chabuduo", 32, "A 跟 B 差不多 — about the same", "他跟我差不多高。",
       "Say two things are about the same.",
       notes="跟/和 B 差不多 (+ adjective).",
       markers=("差不多",), level=3),
    _S("bibushang", 32, "A 比不上 B — can't compare with", "这家比不上那家。",
       "Say one thing is not as good as another.",
       notes="我的华语比不上你.",
       markers=("比不上",), level=3),
    _S("yuqi_buru", 32, "与其……不如…… — rather than …, better to …", "与其等巴士，不如走路。",
       "Weigh two options and recommend the second.",
       notes="Slightly formal; very useful for advice.",
       markers=("与其",), level=4, also_in=(34,)),
    _S("ningke", 32, "宁可 / 宁愿……也不…… — would rather … than", "我宁可走路，也不搭那辆巴士。",
       "Say you'd accept one thing rather than another.",
       notes="宁愿 is the same. Also 宁可……也要…… (would rather … in order to).",
       markers=("宁可", "宁愿"), level=4, also_in=(34,)),

    # ------------------------------------------------------------------
    # 34. Correlatives
    # ------------------------------------------------------------------
    _S("yifangmian", 34, "一方面……另一方面…… — on one hand … on the other", "一方面想省钱，另一方面又想住得舒服。",
       "Weigh two sides of a situation.",
       notes="Formal-ish; common in discussion.",
       markers=("一方面",), level=4),

    # ------------------------------------------------------------------
    # 35. Spoken fluency
    # ------------------------------------------------------------------
    _S("pronoun_context", 35, "Working out who from context", "他 / 她 / 它 — all 'tā'",
       "Follow who or what is meant from context.",
       notes=_SPOKEN + "他/她/它 sound identical: identify tasks where context decides. "
             "Refer back with 这个 / 那件事; things are usually left out rather than "
             "called 它.",
       level=3),
    _S("short_answers", 35, "Short answers — repeat the verb", "你去吗？——去。/ 会不会？——会。",
       "Answer yes or no by repeating the verb.",
       notes=_SPOKEN + "Chinese has no all-purpose yes: 有 / 没有, 喜欢 / 不喜欢, 要 / 不要, "
             "是 / 不是, 可以 / 不可以.",
       level=1, core=True),
    _S("echo_q", 35, "Echo questions — checking what you heard", "什么？/ 明天？/ 三十块？",
       "Check or react to what someone just said.",
       notes=_SPOKEN + "Repeat the surprising part with rising tone, or 你说什么？",
       level=2),
    _S("rhetorical_q", 35, "Rhetorical questions", "你不是说不来吗？/ 这哪里贵？/ 难道你不知道吗？",
       "Make a point with a question that expects no answer.",
       notes=_SPOKEN + "不是……吗？ = weren't you…? (reminder); 哪里 + adjective = not at "
             "all; 难道……吗？ = surely you don't…?; 谁知道？ = who knows.",
       markers=("吗", "哪里", "难道", "谁"), level=4),
    _S("soft_command", 35, "Softening requests", "你帮我看一下啦。/ 请你等一下。/ 来吃吧!",
       "Make a request sound friendly rather than bossy.",
       notes=_SPOKEN + "Soften with 一下, 吧, 啦, 请, 麻烦你, ……好吗？",
       markers=("一下", "吧", "啦", "请", "麻烦", "好吗"), level=2),
    _S("xiang_jiu", 35, "想……就…… — if you want to, then", "想吃就吃!/ 想去就去吧。",
       "Tell someone to go ahead if they want to.",
       notes=_SPOKEN,
       markers=("想",), level=3),
    _S("bu_jiu", 35, "不……就…… — if not …, then …", "你不来就算了。/ 不快点就迟到了。",
       "Say what happens if something isn't done.",
       notes=_SPOKEN + "Often a warning or a shrug (就算了).",
       markers=("不",), level=3),
    _S("dehua", 35, "……的话 — if", "你有空的话，来玩。/ 下雨的话就不去。",
       "Add 'if' at the end of the condition.",
       notes=_SPOKEN + "Alone or with 如果 / 要是 at the start.",
       markers=("的话",), level=2),

    # ------------------------------------------------------------------
    # 36. Core set addition
    # ------------------------------------------------------------------
    _S("dui_laishuo", 36, "对……来说 — for, as far as … is concerned", "对我来说，华语不难。",
       "Give a judgement from someone's point of view.",
       notes="对 + person + 来说 at the start: 对孩子来说太辣了.",
       markers=("来说",), level=3, core=True),
]

LISTED = {
    30: [
        ("不 vs 没", "bu_vs_mei"),
        ("了 vs 过", "le_vs_guo"),
        ("了 vs 着", "le_vs_zhe"),
        ("在 vs 正在 vs 着", "zai_vs_zhe"),
        ("的 vs 得 vs 地", "de_de_de"),
        ("是……的 vs 了", "shi_de_vs_le"),
        ("会 vs 能 vs 可以", "hui_neng_keyi"),
        ("想 vs 要", "xiang_vs_yao"),
        ("要 vs 快要", "yao_vs_kuaiyao"),
        ("来 vs 去", "lai_vs_qu"),
        ("到 vs 在", "dao_vs_zai"),
        ("有 vs 是", "you_vs_shi"),
        ("给 vs 对", "gei_vs_dui"),
        ("跟/和 vs 对", "gen_vs_dui"),
        ("比 vs 没有……那么……", "bi_vs_meiyou"),
        ("跟/和……一样 vs 像……一样", "gen_vs_xiang"),
        ("一样 vs 相似", "yiyang_vs_xiangsi"),
        ("越来越 vs 越……越……", "yue_vs_yuelaiyue"),
        ("又 vs 再", "you_vs_zai"),
        ("又 vs 还", "hai_vs_you"),
        ("还 vs 再", "hai_vs_zai"),
        ("才 vs 就", "cai_vs_jiu"),
        ("只 vs 才", "zhi_vs_cai"),
        ("也 vs 都", "ye_vs_dou"),
        ("都 vs 全", "dou_vs_quan"),
        ("一点 vs 有点", "yidian_vs_youdian"),
        ("几 vs 多少", "ji_vs_duoshao"),
        ("次 vs 遍", "ci_vs_bian"),
        ("一下 vs 一会儿", "yixia_vs_yihui"),
        ("刚 vs 刚才", "gang_vs_gangcai"),
        ("已经 vs 过", "yijing_vs_guo"),
        ("先 vs 再", "xian_vs_zai"),
        ("再 vs 然后", "zai_vs_ranhou"),
        ("只要……就…… vs 只有……才……", "jiu_vs_cai_cond"),
        ("因为……所以…… vs 既然……就……", "yinwei_vs_jiran"),
        ("虽然……但是…… vs 即使……也……", "suiran_vs_jishi"),
        ("如果……就…… vs 只要……就……", "ruguo_vs_zhiyao"),
        ("一……就…… vs 才……就……", "yijiu_vs_caijiu"),
        ("把 vs ordinary active sentence", "ba_vs_active"),
        ("被 vs ordinary active sentence", "bei_vs_active"),
        ("把 vs 被", "ba_vs_bei"),
        ("能/可以 vs 得/不得", "keyi_vs_dei"),
        ("Resultative complement vs potential complement", "res_vs_pot"),
        ("Directional complement vs ordinary location", "dir_vs_prep"),
        ("V + 了 vs V + 过", "le_vs_guo"),
        ("V + 了 vs V + 着", "le_vs_zhe"),
    ],
    31: [
        ("越……越……", "yue_yue"),
        ("越来越……", "yuelaiyue"),
        ("随着…… — as/with…", "suizhe"),
        ("随便…… — casually/whatever", "suibian"),
        ("只好…… — have no choice but", "zhihao"),
        ("只能…… — can only", "zhineng"),
        ("只得…… — have no choice but", "zhihao"),
        ("终于…… — finally", "zhongyu"),
        ("总算…… — finally/at last", "zongsuan"),
        ("果然…… — as expected", "guoran"),
        ("竟然…… — unexpectedly", "jingran"),
        ("居然…… — unexpectedly", "jingran"),
        ("反而…… — instead/on the contrary", "faner"),
        ("甚至…… — even", "shenzhi"),
        ("尤其…… — especially", "youqi"),
        ("特别是…… — especially", "youqi"),
        ("至少…… — at least", "zhishao_zuiduo"),
        ("至多…… — at most", "zhishao_zuiduo"),
        ("差点儿…… — almost", "chadian"),
        ("差一点儿…… — almost", "chadian"),
        ("几乎…… — almost", "jihu"),
        ("幸亏 / 幸好…… — luckily", "xingkui"),
        ("结果…… — as a result", "jieguo"),
        ("因此…… — therefore", "yinci"),
        ("原来…… — it turns out", "yuanlai"),
        ("难怪…… — no wonder", "nanguai"),
        ("看起来…… — it looks/seems", "kan_ting_qilai"),
        ("听起来…… — it sounds", "kan_ting_qilai"),
        ("看来…… — apparently", "kanlai"),
        ("好像…… — seem/as if", "haoxiang"),
        ("似乎…… — seem", "haoxiang"),
        ("据说…… — reportedly", "jushuo"),
        ("听说…… — I hear…", "tingshuo"),
        ("据…… — according to…", "jushuo"),
    ],
    32: [
        ("像……一样……", "xiang_yiyang"),
        ("像……似的", "xiang_shide"),
        ("像……那么……", "xiang_name"),
        ("像……这么……", "xiang_name"),
        ("跟……一样……", "gen_yiyang"),
        ("和……一样……", "gen_yiyang"),
        ("跟……差不多", "gen_chabuduo"),
        ("和……差不多", "gen_chabuduo"),
        ("不如……", "buru"),
        ("比不上……", "bibushang"),
        ("比……还……", "bi_hai"),
        ("比……更……", "bi_geng"),
        ("没有……那么……", "meiyou_name"),
        ("越……越……", "yue_yue"),
        ("越来越……", "yuelaiyue"),
        ("与其……不如……", "yuqi_buru"),
        ("宁可……也不……", "ningke"),
        ("宁愿……也不……", "ningke"),
    ],
    33: [
        ("只要……就……", "zhiyao_jiu"),
        ("只有……才……", "zhiyou_cai"),
        ("如果……就……", "ruguo_jiu"),
        ("要是……就……", "yaoshi_jiu"),
        ("假如……就……", "jiaru"),
        ("除非……否则……", "chufei_fouze"),
        ("除非……才……", "chufei_cai"),
        ("无论……都……", "wulun_dou"),
        ("不管……都……", "buguan_dou"),
        ("不论……都……", "wulun_dou"),
        ("即使……也……", "jishi_ye"),
        ("哪怕……也……", "napa_ye"),
        ("就算……也……", "jiusuan_ye"),
        ("即便……也……", "jishi_ye"),
        ("哪怕……也……", "napa_ye"),
        ("无论……还是……", "wulun_dou"),
        ("不管……还是……", "buguan_dou"),
    ],
    34: [
        ("一……就……", "yi_jiu"),
        ("越……越……", "yue_yue"),
        ("越来越……", "yuelaiyue"),
        ("又……又……", "you_you"),
        ("一边……一边……", "yibian"),
        ("一面……一面……", "yibian"),
        ("既……又……", "ji_you"),
        ("不但……而且……", "budan_erqie"),
        ("不仅……还……", "bujin_hai"),
        ("虽然……但是……", "suiran_danshi"),
        ("因为……所以……", "yinwei_suoyi"),
        ("既然……就……", "jiran_jiu"),
        ("只要……就……", "zhiyao_jiu"),
        ("只有……才……", "zhiyou_cai"),
        ("如果……就……", "ruguo_jiu"),
        ("无论……都……", "wulun_dou"),
        ("即使……也……", "jishi_ye"),
        ("除了……以外……", "chule_hai"),
        ("不是……而是……", "bushi_ershi"),
        ("与其……不如……", "yuqi_buru"),
        ("宁可……也……", "ningke"),
        ("一方面……另一方面……", "yifangmian"),
    ],
    35: [
        ("Topic fronting", "topic_comment"),
        ("Topic-comment sentences", "topic_comment"),
        ("Omitted subjects", "subject_omission"),
        ("Omitted objects", "object_omission"),
        ("Omitted repeated information", "fragments"),
        ("Context-dependent pronouns", "pronoun_context"),
        ("Short answer patterns", "short_answers"),
        ("Repetition for emphasis", "repeat_emphasis"),
        ("Verb reduplication", "redup_verb"),
        ("Adjective reduplication", "redup_adj"),
        ("Echo questions", "echo_q"),
        ("A-not-A questions", "a_not_a"),
        ("Rhetorical questions", "rhetorical_q"),
        ("Sentence-final particles", "my_particles"),
        ("Softened commands", "soft_command"),
        ("Suggestions with 吧", "ba_particle"),
        ("Confirmation with 对不对 / 是不是", "tag_q"),
        ("想……就…… — if you want…then…", "xiang_jiu"),
        ("要……就…… — if you want/need…then…", "yao_jiu"),
        ("不……就…… — if not…then…", "bu_jiu"),
        ("……的话…… — if…", "dehua"),
        ("要是……的话……", "yaoshi_jiu"),
        ("如果……的话……", "ruguo_jiu"),
        ("……的时候……", "de_shihou"),
        ("……的时候就……", "de_shihou"),
        ("……以后再……", "yihou_zai"),
        ("……以前先……", "zhiqian_xian"),
    ],
    36: [
        ("Basic word order", "word_order"),
        ("的", "de_possessive"),
        ("不 / 没", "bu_vs_mei"),
        ("在 / 正在", "zai_v"),
        ("了", "le_verb"),
        ("过", "guo_exp"),
        ("着", "zhe_state"),
        ("Question words", "qword_position"),
        ("吗 / A-not-A", "ma_question"),
        ("Measure words", "num_mw_noun"),
        ("Duration", "dur_basic"),
        ("Frequency", "ci_times"),
        ("Modal verbs", "hui_neng_keyi"),
        ("Resultative complements", "res_wan"),
        ("Potential complements", "pot_bu"),
        ("Directional complements", "dir_compound"),
        ("比", "bi_adj"),
        ("没有……那么……", "meiyou_name"),
        ("跟/和……一样", "gen_yiyang"),
        ("像……一样", "xiang_yiyang"),
        ("越……越……", "yue_yue"),
        ("越来越……", "yuelaiyue"),
        ("把", "ba_basic"),
        ("被", "bei_basic"),
        ("是……的", "shi_de"),
        ("才 / 就", "cai_vs_jiu"),
        ("又 / 再", "you_vs_zai"),
        ("还 / 又", "hai_vs_you"),
        ("只要……就……", "zhiyao_jiu"),
        ("只有……才……", "zhiyou_cai"),
        ("如果……就……", "ruguo_jiu"),
        ("一……就……", "yi_jiu"),
        ("因为……所以……", "yinwei_suoyi"),
        ("既然……就……", "jiran_jiu"),
        ("虽然……但是……", "suiran_danshi"),
        ("即使……也……", "jishi_ye"),
        ("无论……都……", "wulun_dou"),
        ("除了……以外……", "chule_hai"),
        ("连……都/也……", "lian_dou"),
        ("一边……一边……", "yibian"),
        ("不但……而且……", "budan_erqie"),
        ("不是……而是……", "bushi_ershi"),
        ("对……来说……", "dui_laishuo"),
        ("Relative clauses with 的", "rel_v_de"),
        ("Prepositional phrases", "gen_with"),
        ("Serial verbs", "serial_verbs"),
        ("Verb reduplication", "redup_verb"),
        ("Sentence-final particles", "ba_particle"),
        ("Spoken ellipsis", "fragments"),
        ("Topic-comment structures", "topic_comment"),
    ],
}
