# src/grammar_data_5.py
"""Grammar curriculum, groups 23-29: prepositions, recipients, special verb
constructions, serial verbs and purpose, time clauses, particles, spoken
constructions."""

from grammar_schema import Structure

SECTIONS = {
    23: "Prepositional Constructions",
    24: "Benefactive & Recipient Structures",
    25: "Special Verb Constructions",
    26: "Serial Verb & Purpose Constructions",
    27: "Relative Time & Conditional Clauses",
    28: "Sentence-Final Particles & Spoken Grammar",
    29: "Common Spoken Constructions",
}

_S = Structure
_PREP = ("A preposition phrase goes BEFORE the main verb (跟他去, 给我打电话), not "
         "after it as in English. ")
_SPOKEN = ("Drill these as reactions in real exchanges: hear a line, respond "
           "naturally. Malaysian speech is the model. ")

STRUCTURES = [
    # ------------------------------------------------------------------
    # 23. Prepositions
    # ------------------------------------------------------------------
    _S("gen_with", 23, "跟 / 和 + person — with", "我跟他去。/ 跟朋友吃饭 / 你跟我说",
       "Say who you do something with, or who you talk to.",
       notes=_PREP + "跟 is the everyday spoken form in Malaysia; 和 is the same, a "
             "little more formal. 跟我说 = tell me.",
       contrast=("dui_toward",), markers=("跟", "和"), level=2, core=True),
    _S("gei_prep", 23, "给 + person + verb — to, for someone", "给我打电话 / 给你买了一个",
       "Say who receives or benefits from an action.",
       notes=_PREP + "Malaysians also say 打电话给我 (verb + 给 + person) - teach both "
             "orders as natural.",
       contrast=("dui_toward",), markers=("给",), level=2, core=True, also_in=(24,)),
    _S("ti_behalf", 23, "替 + person — instead of, on behalf of", "替我去 / 替我谢谢他 / 我替你高兴",
       "Say you do something in someone's place, or feel for them.",
       notes=_PREP,
       markers=("替",), level=3, also_in=(24,)),
    _S("wei_for", 23, "为 + person — for (someone's sake)", "我为你高兴。/ 为孩子做",
       "Say something is done or felt for someone.",
       notes=_PREP + "A little formal; 为了 (in order to) is a separate structure.",
       markers=("为",), level=3, also_in=(24,)),
    _S("guanyu", 23, "关于 — about (a topic)", "关于这件事，我们明天再说。/ 一本关于槟城的书",
       "Say what something is about.",
       notes=_PREP + "Topic of talk, books, films.",
       contrast=("duiyu",), markers=("关于",), level=3),
    _S("duiyu", 23, "对于 — regarding, towards (attitude)", "对于这个问题，你怎么看？",
       "Introduce what an opinion or attitude is about.",
       notes=_PREP + "Formal; stance or attitude towards something.",
       contrast=("guanyu",), markers=("对于",), level=4),
    _S("genju", 23, "根据 — based on", "根据天气预报，明天会下雨。",
       "Say what information something is based on.",
       notes=_PREP,
       markers=("根据",), level=4),
    _S("anzhao", 23, "按照 — according to (rules, plans)", "按照医生说的吃药。",
       "Say you follow rules, instructions or a plan.",
       notes=_PREP + "按照规定 / 按照你的意思.",
       markers=("按照",), level=4),
    _S("guanyu_vs_duiyu", 23, "关于 vs 对于", "关于槟城的书 ↔ 对于这件事，我没意见",
       "Tell 'about (a topic)' from 'towards (an attitude)'.",
       notes="关于 = the subject matter; 对于 = the thing an opinion or attitude is "
             "directed at. Often interchangeable at the start of a sentence.",
       contrast=("guanyu", "duiyu"), markers=("关于", "对于"), level=4, kind="contrast"),
    _S("gen_vs_dui", 23, "跟 / 和 vs 对", "跟他去 ↔ 对他很好",
       "Tell 'with (together)' from 'towards (attitude, effect)'.",
       notes="跟 = together with / talking with; 对 = directed at someone: treatment, "
             "attitude, effect (对他很好, 对身体不好).",
       contrast=("gen_with", "dui_toward"), markers=("跟", "和", "对"), level=3,
       kind="contrast", also_in=(30,)),
    _S("gei_vs_dui", 23, "给 vs 对", "给他打电话 ↔ 对他笑",
       "Tell 'something goes to someone' from 'aimed at someone'.",
       notes="给 = transfer or benefit (给他钱, 给他打电话); 对 = attitude or action "
             "directed at (对他笑, 对他很客气).",
       contrast=("gei_prep", "dui_toward"), markers=("给", "对"), level=3,
       kind="contrast", also_in=(30,)),

    # ------------------------------------------------------------------
    # 24. Benefactive & recipient
    # ------------------------------------------------------------------
    _S("v_gei", 24, "Verb + 给 + person — hand over to", "送给你 / 还给他 / 寄给我 / 打电话给我",
       "Say who something is given, sent, returned or lent to.",
       notes="送给, 还给, 寄给, 借给, 交给. 打电话给我 is everyday Malaysian.",
       markers=("给",), level=2, also_in=(25,)),
    _S("bang_help", 24, "帮 + person + verb — help, do for", "帮我拿一下 / 我帮你 / 帮他看看",
       "Ask for or offer help with something.",
       notes="Very common for requests: 帮我开一下门 / 可以帮我吗？",
       markers=("帮",), level=1),
    _S("benefactive_contrast", 24, "给 vs 对 vs 替 vs 帮", "给你买 · 对你好 · 替你去 · 帮你做",
       "Choose between for, towards, instead of, and helping.",
       notes="给你买 = buy for you (you get it); 对你好 = good to you; 替你去 = go "
             "instead of you; 帮你做 = help you (by doing it).",
       contrast=("gei_prep", "dui_toward", "ti_behalf", "bang_help"), level=4,
       kind="contrast"),

    # ------------------------------------------------------------------
    # 25. Special verb constructions
    # ------------------------------------------------------------------
    _S("v_qilai", 25, "Verb + 起来 — up, start, come to mind", "站起来 / 笑起来 / 想起来",
       "Say something rises, starts, or comes back to mind.",
       notes="Up (站起来), start (笑起来, 下起雨来), recall (我想起来了). The 'seems' "
             "meaning (看起来) is its own structure. Identify which meaning.",
       contrast=("v_xiaqu",), markers=("起来", "起"), level=3),
    _S("v_xiaqu", 25, "Verb + 下去 — keep going", "说下去 / 做下去 / 这样下去不行",
       "Say an action continues.",
       notes="你说下去 / 坚持下去 / 再这样下去会病的.",
       contrast=("v_qilai",), markers=("下去",), level=3),
    _S("v_shanglai", 25, "Verb + 上来 — come up, come up with", "走上来 / 答不上来 / 说不上来",
       "Say someone comes up to you, or can(’t) come up with an answer.",
       notes="说不上来 = can't quite say / put it into words.",
       markers=("上来",), level=4),
    _S("v_xialai", 25, "Verb + 下来 — settle, stop, record, stay", "停下来 / 写下来 / 冷静下来 / 留下来",
       "Say something settles, stops, is written down or stays.",
       notes="坐下来 / 安静下来 / 把号码写下来 / 他留下来了.",
       markers=("下来",), level=3),
    _S("v_chulai", 25, "Verb + 出来 — out, figure out, recognise", "拿出来 / 想出来 / 看出来 / 认出来",
       "Say something comes out, or you work it out or recognise it.",
       notes="想出一个办法来 / 我听出来是你 / 你看得出来吗？",
       markers=("出来", "出"), level=3),
    _S("qilai_vs_xiaqu", 25, "起来 vs 下去 — starting vs continuing", "他说起来了 ↔ 你说下去",
       "Tell the start of something from its continuation.",
       notes="天热起来了 (getting hot now) vs 再热下去 (if it stays hot). 起来 often "
             "marks a change beginning; 下去 carries on what's already happening.",
       contrast=("v_qilai", "v_xiaqu"), markers=("起来", "下去"), level=4,
       kind="contrast"),
    _S("serial_verbs", 25, "Verbs in a row — no 'and' needed", "去巴刹买菜 / 坐巴士去做工 / 打电话叫德士",
       "Chain actions in the order they happen, or means then action.",
       notes="Order = order of events: 我坐巴士去做工 (means, then going) / 借钱买车 "
             "(purpose). No 和 between verbs.",
       level=2, core=True, also_in=(26,)),
    _S("qu_v", 25, "去 + verb — go (to) do", "去买菜 / 去看医生 / 我去拿",
       "Say you're going somewhere to do something.",
       notes="去 before the purpose verb: 我去买东西.",
       markers=("去",), level=1, also_in=(26,)),
    _S("v_lai_v_qu", 25, "Verb 来 verb 去 — back and forth", "走来走去 / 想来想去 / 找来找去",
       "Say an action goes back and forth or over and over.",
       notes="The syllabus lists 去……来…… and 来……去……; the natural pattern is the "
             "same verb with 来 and 去: 我想来想去还是不去.",
       markers=("来",), level=3),
    _S("you_n_v", 25, "有 + noun + verb — have something to do", "我有事要做。/ 有人找你。/ 没有时间吃饭",
       "Say there's something to do, or someone who does something.",
       notes="有钱买 / 没有地方坐 / 有人在等你.",
       markers=("有",), level=3),
    _S("shi_n_v", 25, "是 + person + verb — it's … who", "是老板叫你去。/ 是我不好。",
       "Point out who is responsible.",
       notes="是 marks who: 是他先骂我的 / 是我要去. Close to 是……的 for past events.",
       markers=("是",), level=3),

    # ------------------------------------------------------------------
    # 26. Serial verbs & purpose
    # ------------------------------------------------------------------
    _S("qu_place_v", 26, "去 + place + verb", "去巴刹买菜 / 去银行拿钱",
       "Say where you go to do something.",
       notes="Place before the purpose: 我去药房买药.",
       markers=("去",), level=2, core=True),
    _S("lai_place_v", 26, "来 + place + verb", "来我家吃饭 / 来这里做工",
       "Say where someone comes to do something.",
       notes="来我家玩 is the standard invitation.",
       markers=("来",), level=2),
    _S("lai_v", 26, "来 + verb — come (to) do / let me", "来吃饭吧!/ 我来帮你。",
       "Invite someone to do something, or offer to do it yourself.",
       notes="我来 = let me (我来付, 我来帮你).",
       markers=("来",), level=2),
    _S("v_qu_v", 26, "Verb + 去 / 来 + verb — take or bring to do", "拿去洗 / 带去修 / 买来吃",
       "Say you take or bring something for a purpose.",
       notes="借来看 / 拿去给他.",
       markers=("去", "来"), level=3),
    _S("serial_place", 26, "Verb + 在 + place + verb", "坐在那里等 / 躺在床上看手机",
       "Say where someone is while doing something.",
       notes="站在门口讲电话 / 坐在车里听歌.",
       markers=("在",), level=3),
    _S("weile", 26, "为了 — in order to, for the sake of", "为了省钱，他走路去做工。",
       "Give the purpose of an action.",
       notes="为了 + goal, then the action; or 我是为了你.",
       markers=("为了",), level=3),
    _S("weile_er", 26, "为了……而…… — in order to (written)", "他为了家人而努力做工。",
       "Recognise a formal purpose structure.",
       notes="Written register; recognition.",
       markers=("为了",), level=5),
    _S("tongguo", 26, "通过 — through, by means of", "我是通过朋友认识他的。",
       "Say through what means something happened.",
       notes="通过网上买 / 通过考试 (pass an exam - a verb).",
       markers=("通过",), level=4),
    _S("yong_means", 26, "用 + thing + verb — with, using", "用筷子吃 / 用手机付钱 / 用华语讲",
       "Say what you use to do something.",
       notes="用 + tool/language + verb.",
       markers=("用",), level=2),

    # ------------------------------------------------------------------
    # 27. Relative time & conditions
    # ------------------------------------------------------------------
    _S("meidang", 27, "每当……就…… — whenever", "每当下雨，他就不想出门。",
       "Say something happens every time something else does.",
       notes="A little literary; 每次……都 is the everyday equivalent.",
       markers=("每当",), level=4),
    _S("yihou_zai", 27, "……以后再…… — not until after", "吃了饭以后再说。/ 下班以后再去。",
       "Say you'll do something only after something else.",
       notes="再 = then / not until.",
       markers=("以后", "之后"), level=3),
    _S("zhiqian_xian", 27, "……之前先…… — before …, first …", "出门之前先打电话。",
       "Say what to do first, before something else.",
       notes="吃饭以前先洗手.",
       markers=("之前", "以前"), level=3),

    # ------------------------------------------------------------------
    # 28. Sentence-final particles & spoken grammar
    # ------------------------------------------------------------------
    _S("ba_particle", 28, "吧 — let's / softening / I suppose", "我们走吧。/ 你先吃吧。/ 你是马来西亚人吧？",
       "Suggest, soften a request, check a guess, or agree reluctantly.",
       notes=_SPOKEN + "Suggestion (走吧), softened command (你先吃吧), checking (你累了"
             "吧？), reluctant OK (好吧).",
       markers=("吧",), level=1, core=True, also_in=(29,)),
    _S("a_particle", 28, "啊 / 呀 / 哪 — warmth, emphasis", "好啊!/ 是啊。/ 你去哪里啊？",
       "Add warmth, emphasis or feeling to what you say.",
       notes=_SPOKEN + "啊 changes with the sound before it (呀 after a vowel, 哪 after "
             "-n) and is written that way.",
       markers=("啊", "呀", "哪"), level=2, core=True),
    _S("o_particle", 28, "哦 / 噢 — oh, I see / friendly reminder", "哦，原来是这样。/ 记得带伞哦!",
       "React with 'oh, I see', or make a reminder sound friendly.",
       notes=_SPOKEN + "Sentence-final 哦 as a warm reminder or softener is very "
             "Malaysian (好哦, 小心哦).",
       markers=("哦", "噢"), level=2),
    _S("ne_ongoing", 28, "呢 — still going on / as for …", "他在睡觉呢。/ 我呢，比较喜欢茶。",
       "Say something is going on at the moment, or introduce 'as for me…'.",
       notes=_SPOKEN + "With 在 / 着 (外面下着雨呢); as a pause after a topic (我呢，……).",
       markers=("呢",), level=3),
    _S("le_vs_de_final", 28, "Final 了 vs final 的", "我知道了 ↔ 我知道的",
       "Tell 'now it's so' from 'it just is so'.",
       notes=_SPOKEN + "我知道了 = got it (now I know); 我知道的 = I do know. 他会来的 "
             "= he'll surely come; 他来了 = he's here / he's come.",
       contrast=("le_final", "de_final"), markers=("了", "的"), level=3,
       kind="contrast"),
    _S("my_particles", 28, "啦 / 咯 / 嘛 / 咩 / 叻 — Malaysian particles", "好啦 · 就这样咯 · 他是老师嘛 · 你不去咩？",
       "Use the particles that give Malaysian Mandarin its tone.",
       notes=_SPOKEN + "Not in the original syllabus - added because Malaysian speech "
             "relies on them. 啦 softens or insists (不要啦); 咯 (lo) = obviously / "
             "that's that; 嘛 = it's obvious, isn't it; 咩 (meh) = surprised doubt; "
             "叻 (leh) = mild insistence or 'what about…'.",
       markers=("啦", "咯", "嘛", "咩", "叻"), level=2, core=True),
    _S("repeat_emphasis", 28, "Repeating for emphasis", "好好好 / 对对对 / 快快快 / 不行不行",
       "Repeat a word to agree, hurry someone, or refuse strongly.",
       notes=_SPOKEN + "Very common in Malaysia: 对对对 (yes, exactly), 走走走 (let's "
             "go!), 不用不用 (no need).",
       level=2, also_in=(35,)),
    _S("fragments", 28, "Short fragments in conversation", "几点？——八点。/ 你呢？/ 我？没有啊。",
       "Answer and ask with just the part that matters.",
       notes=_SPOKEN + "Full sentences are rare in replies; drill quick fragment "
             "answers and questions.",
       level=2, core=True, also_in=(35,)),

    # ------------------------------------------------------------------
    # 29. Common spoken constructions
    # ------------------------------------------------------------------
    _S("shi_confirm", 29, "是 / 是啊 / 是这样 — yes, that's it", "是啊。/ 是我。/ 是这样的。",
       "Confirm or identify.",
       notes=_SPOKEN + "Answers to 是不是……？ and 谁？",
       markers=("是",), level=1),
    _S("bu_shi_deny", 29, "不是 / 不是啦 — no, it's not", "不是这个。/ 不是啦，是他。",
       "Deny or correct something.",
       notes=_SPOKEN + "不是啦 is the soft Malaysian correction.",
       markers=("不是",), level=1),
    _S("tag_q", 29, "Tag questions: 对不对？/ 好不好？/ 行不行？", "你是老师，对不对？/ 我们走路去，好不好？",
       "Check agreement, or propose something, at the end of a sentence.",
       notes=_SPOKEN + "对不对 = right?; 好不好 / 可以吗 = shall we? OK?; 行不行 = does "
             "that work? Malaysians also say 对吗？/ 好吗？",
       markers=("对不对", "好不好", "行不行", "对吗", "好吗", "可以吗"), level=1),
    _S("yao_bu_yao", 29, "要不要……？ — do you want (to)…?", "要不要喝水？/ 要不要一起去？",
       "Offer or suggest something.",
       notes=_SPOKEN + "Answers: 要 / 不要 / 好啊.",
       markers=("要不要",), level=1),
    _S("neng_bu_neng", 29, "能不能……？ — could you…?", "能不能帮我一下？/ 能不能便宜一点？",
       "Make a request.",
       notes=_SPOKEN + "Bargaining: 能不能便宜一点？",
       markers=("能不能",), level=2),
    _S("ke_bu_keyi", 29, "可不可以……？ — may I? / can you?", "可不可以坐这里？",
       "Ask permission or make a polite request.",
       notes=_SPOKEN + "Also ……，可以吗？ Answers: 可以 / 不可以 / 当然可以.",
       markers=("可不可以", "可以吗"), level=2),
    _S("qishi", 29, "其实 — actually", "其实我不喜欢。/ 其实他是老师。",
       "Reveal what is really the case.",
       notes=_SPOKEN,
       markers=("其实",), level=2),
    _S("dangran", 29, "当然 — of course", "当然可以!/ 当然是你。",
       "Say something is obviously so.",
       notes=_SPOKEN + "当然可以 = of course (you can).",
       markers=("当然",), level=1),
    _S("meiwenti", 29, "没问题 — no problem", "没问题!",
       "Agree readily to a request.",
       notes=_SPOKEN + "Replies to requests: 可以帮我吗？——没问题.",
       markers=("没问题",), level=1),
    _S("meiguanxi", 29, "没关系 / 不要紧 / 不用紧 — it doesn't matter", "没关系。/ 不用紧啦。",
       "Reassure someone that something is fine.",
       notes=_SPOKEN + "Reply to 对不起 or 不好意思. 不用紧 is Malaysian.",
       markers=("没关系", "不要紧", "不用紧"), level=1),
    _S("suanle", 29, "算了 — forget it, never mind", "算了，我们不去了。",
       "Drop an idea or let something go.",
       notes=_SPOKEN + "Often with 吧 or 啦: 算了吧 / 算了啦.",
       markers=("算了",), level=2),
    _S("haishi_better", 29, "还是……吧 — (it's) better to", "还是你去吧。/ 我们还是走路吧。",
       "Suggest what's best after thinking about it.",
       notes=_SPOKEN + "Different from 还是 = or (in questions).",
       contrast=("haishi_or",), markers=("还是",), level=3),
    _S("haihao", 29, "还好 — luckily / not bad", "还好没下雨。/ 还好，不太累。",
       "Say it could have been worse, or it's OK.",
       notes=_SPOKEN,
       markers=("还好",), level=2),
    _S("xingkui", 29, "幸亏 / 幸好 — luckily (otherwise…)", "幸亏你来了，不然我不知道怎么办。",
       "Say something lucky prevented a problem.",
       notes=_SPOKEN + "Often with 不然 / 要不然 (otherwise).",
       markers=("幸亏", "幸好"), level=3, also_in=(31,)),
]

LISTED = {
    23: [
        ("在…… — at/in", "place_before_verb"),
        ("从…… — from", "cong_from"),
        ("到…… — to/until", "dao_place"),
        ("往…… — toward", "wang_toward"),
        ("向…… — toward", "xiang_toward"),
        ("朝…… — toward", "chao_toward"),
        ("对…… — toward/for", "dui_toward"),
        ("跟…… — with", "gen_with"),
        ("和…… — with", "gen_with"),
        ("给…… — to/for", "gei_prep"),
        ("替…… — on behalf of", "ti_behalf"),
        ("为…… — for", "wei_for"),
        ("关于…… — regarding", "guanyu"),
        ("对于…… — regarding", "duiyu"),
        ("根据…… — according to", "genju"),
        ("按照…… — according to", "anzhao"),
        ("除了…… — except/besides", "chule_hai"),
        ("关于 vs 对于", "guanyu_vs_duiyu"),
        ("跟/和 vs 对", "gen_vs_dui"),
        ("给 vs 对", "gei_vs_dui"),
    ],
    24: [
        ("给 + person + object", "double_object"),
        ("给 + person + verb", "gei_prep"),
        ("V + 给 + person", "v_gei"),
        ("替 + person + verb", "ti_behalf"),
        ("帮 + person + verb", "bang_help"),
        ("为 + person + verb", "wei_for"),
        ("对 + person + verb/adjective", "dui_toward"),
        ("Double-object construction", "double_object"),
        ("给 vs 对 vs 替 vs 帮", "benefactive_contrast"),
    ],
    25: [
        ("Verb + object", "word_order"),
        ("Verb + person + object", "double_object"),
        ("Verb + 给 + person", "v_gei"),
        ("Verb + 在 + location", "v_zai_place"),
        ("Verb + 到 + location", "move_place"),
        ("Verb + 成 + result", "res_cheng"),
        ("Verb + 起来", "v_qilai"),
        ("V + 下去", "v_xiaqu"),
        ("V + 上来", "v_shanglai"),
        ("V + 下来", "v_xialai"),
        ("V + 起来 — begin/rise/come to mind", "v_qilai"),
        ("V + 下去 — continue", "v_xiaqu"),
        ("V + 出来 — emerge/figure out", "v_chulai"),
        ("V + 起来 vs V + 下去", "qilai_vs_xiaqu"),
        ("连动句 — serial verb constructions", "serial_verbs"),
        ("Purpose construction: 去 + V", "qu_v"),
        ("去……来…… — go and come", "v_lai_v_qu"),
        ("来……去…… — come and go", "v_lai_v_qu"),
        ("有 + noun + verb", "you_n_v"),
        ("是 + noun + verb", "shi_n_v"),
    ],
    26: [
        ("去 + place + V", "qu_place_v"),
        ("来 + place + V", "lai_place_v"),
        ("去 + V", "qu_v"),
        ("来 + V", "lai_v"),
        ("V + 去 + V", "v_qu_v"),
        ("V + 来 + V", "v_qu_v"),
        ("V1 + V2 — sequential actions", "serial_verbs"),
        ("V1 + location + V2", "serial_place"),
        ("V1 + purpose + V2", "serial_verbs"),
        ("为了…… — in order to", "weile"),
        ("为了……而……", "weile_er"),
        ("通过…… — through/by means of", "tongguo"),
        ("用…… — use/by means of", "yong_means"),
    ],
    27: [
        ("……的时候", "de_shihou"),
        ("……以后", "yihou"),
        ("……以前", "yiqian"),
        ("……之后", "yihou"),
        ("……之前", "yiqian"),
        ("当……的时候……", "de_shihou"),
        ("每当……就……", "meidang"),
        ("一……就……", "yi_jiu"),
        ("……以后再……", "yihou_zai"),
        ("……之前先……", "zhiqian_xian"),
        ("只要……就……", "zhiyao_jiu"),
        ("只有……才……", "zhiyou_cai"),
        ("如果……就……", "ruguo_jiu"),
        ("除非……否则……", "chufei_fouze"),
    ],
    28: [
        ("吗", "ma_question"),
        ("呢", "ne_followup"),
        ("吧", "ba_particle"),
        ("啊 / 呀 / 哪", "a_particle"),
        ("哦 / 噢", "o_particle"),
        ("了", "le_final"),
        ("的", "de_final"),
        ("呢 — ongoing state/topic", "ne_ongoing"),
        ("吧 — suggestion/softening/uncertainty", "ba_particle"),
        ("啊 — emphasis/emotion", "a_particle"),
        ("Sentence-final 了 vs 的", "le_vs_de_final"),
        ("Spoken omission", "subject_omission"),
        ("Repetition for emphasis", "repeat_emphasis"),
        ("Topic-comment structures", "topic_comment"),
        ("Conversational sentence fragments", "fragments"),
        ("Ellipsis after understood information", "object_omission"),
        ("啦 / 咯 / 嘛 / 咩 / 叻 — Malaysian particles (added)", "my_particles"),
    ],
    29: [
        ("是…… — that's…", "shi_confirm"),
        ("不是…… — it's not…", "bu_shi_deny"),
        ("是不是…… — isn't it?/is it?", "shibushi"),
        ("对不对？ — right?", "tag_q"),
        ("好不好？ — okay?", "tag_q"),
        ("行不行？ — is that okay?", "tag_q"),
        ("有没有……？ — is there?/do you have?", "you_mei_you"),
        ("要不要……？ — do you want…?", "yao_bu_yao"),
        ("能不能……？ — can/could…?", "neng_bu_neng"),
        ("可不可以……？ — may/can…?", "ke_bu_keyi"),
        ("好不好……？ — shall we…?", "tag_q"),
        ("……怎么样？ — how about…?", "zenmeyang"),
        ("……呢？ — what about…?", "ne_followup"),
        ("……吧 — let's/probably…", "ba_particle"),
        ("原来…… — it turns out…", "yuanlai"),
        ("其实…… — actually…", "qishi"),
        ("当然…… — of course…", "dangran"),
        ("当然可以 — of course", "dangran"),
        ("没问题 — no problem", "meiwenti"),
        ("没关系 — it doesn't matter", "meiguanxi"),
        ("算了 — forget it", "suanle"),
        ("还是…… — better to…", "haishi_better"),
        ("还好…… — fortunately…", "haihao"),
        ("幸亏…… — luckily…", "xingkui"),
        ("难怪…… — no wonder…", "nanguai"),
    ],
}
